### PR TITLE
swarm: cleanup created resources for fuse

### LINKED ISSUE #648: tests stall in the swarm/fuse package sometimes
Running tests in the `swarm/fuse` package sometimes stall

#### System information
Linux
happens on the `swarm-network-rewrite` branch

#### Expected behaviour
Tests complete

#### Actual behaviour
Tests stall.
There is no cleanup of any temporary resource created in `/tmp`
When it hangs, it hangs in a somewhat ugly way: `ls /tmp` in an unrelated, separate terminal hangs too! System resources are locked up and only freed after rebooting, killing the process doesn't work properly.

#### Steps to reproduce the behaviour
Run the tests in the fuse package

### PR DESCRIPTION
**Pull request by holisticode**
addresses #591 
fixes #648

Cleanup and remove created directories.

### CODE REVIEW

**Review by acud — APPROVED** [review]
LGTM except for the two small comments

File: swarm/fuse/swarmfs_unix.go [hunk 1]
```diff
@@ -155,30 +155,24 @@ func (swarmfs *SwarmFS) Mount(mhash, mountpoint string) (*MountInfo, error) {
...
-
 	case <-fconn.Ready:
 		log.Info("swarmfs now served over FUSE", "manifest", mhash, "mountpoint", cleanedMountPoint)
+		go func() {
+			log.Info("swarmfs", "serving hash", mhash, "at", cleanedMountPoint)
+			filesys := &SwarmRoot{root: rootDir}
+			if err := fs.Serve(fconn, filesys); err != nil {
+				log.Warn("swarmfs error serving over FUSE", "mountpoint", cleanedMountPoint, "err", err)
+				fuse.Unmount(cleanedMountPoint)
+				return
```
[the remark this answers is not in the document]
Comment (holisticode) [reply swarm/fuse/swarmfs_unix.go]: in fact no :)

File: swarm/fuse/swarmfs_test.go [hunk 2]
```diff
@@ -242,282 +249,385 @@ func (ta *testAPI) mountListAndUnmount(t *testing.T, toEncrypt bool) {
...
-
-	// try mounting the same hash second time
-	os.RemoveAll(testMountDir2)
-	os.MkdirAll(testMountDir2, 0777)
+	defer os.RemoveAll(testMountDir2)
 	_, err := swarmfs.Mount(bzzHash1, testMountDir2)
 	if err != nil {
 		t.Fatalf("Error mounting hash  %v", bzzHash1)
 	}
+	swarmfs.Unmount(testMountDir2)
```
Comment (zelig) [inline swarm/fuse/swarmfs_test.go]: this returns error why not check?

File: swarm/fuse/swarmfs_test.go [hunk 3]
```diff
@@ -242,282 +249,385 @@ func (ta *testAPI) mountListAndUnmount(t *testing.T, toEncrypt bool) {
...
+	log.Info("Remount hash1 successful")
 
 	// mount a different hash in already mounted point
 	_, err = swarmfs.Mount(bzzHash2, testMountDir1)
 	if err == nil {
 		t.Fatalf("Error mounting hash  %v", bzzHash2)
 	}
+	log.Info("Remount hash2 successful")
```
Comment (zelig) [inline swarm/fuse/swarmfs_test.go]: incorrect log msg

File: swarm/fuse/swarmfs_test.go [hunk 4]
```diff
@@ -242,282 +249,385 @@ func (ta *testAPI) mountListAndUnmount(t *testing.T, toEncrypt bool) {
...
 
 	// mount nonexistent hash
 	_, err = swarmfs.Mount("0xfea11223344", testMountDir1)
 	if err == nil {
 		t.Fatalf("Error mounting hash  %v", bzzHash2)
```
Comment (zelig) [inline swarm/fuse/swarmfs_test.go]: incorrect error msg

File: swarm/fuse/swarmfs_test.go [hunk 5]
```diff
@@ -242,282 +249,385 @@ func (ta *testAPI) mountListAndUnmount(t *testing.T, toEncrypt bool) {
...
 
 	files["1.txt"] = fileInfo{0700, 333, 444, getRandomBytes(10)}
 	bzzHash := createTestFilesAndUploadToSwarm(t, ta.api, files, uploadDir, toEncrypt)
+	log.Info("Created test files and uploaded to swarm with uploadDir")
 
 	swarmfs := mountDir(t, ta.api, files, bzzHash, testMountDir)
+	log.Info("Mounted Dir")
 	defer swarmfs.Stop()
 
 	swarmfs.Unmount(testMountDir)
```
Comment (zelig) [inline swarm/fuse/swarmfs_test.go]: error check?

**Review by zelig — CHANGES_REQUESTED** [review]
`ioutil.TempDir` should be called and cleaned up only once. return ERROR should be checked.
from then on subdirs can be created, no deffer remove needed on them

`Unmount` calls return an error which needs to be checked.

`io.File` methods like `Write`, `Seek`, `Close`, `Sync` all return errors which need checking

after a while i just stopped putting comments.
`rand.Read` returns an error too

File: swarm/fuse/swarmfs_test.go [hunk 6]
```diff
@@ -55,7 +55,7 @@ type fileInfo struct {
 }
 
 func createTestFilesAndUploadToSwarm(t *testing.T, api *api.Api, files map[string]fileInfo, uploadDir string, toEncrypt bool) string {
-	os.RemoveAll(uploadDir)
+	//os.RemoveAll(uploadDir)
```
Comment (gbalint) [inline swarm/fuse/swarmfs_test.go]: Please don't leave commented code, delete it if it is not needed

File: swarm/fuse/swarmfs_test.go [hunk 7]
```diff
@@ -212,17 +213,23 @@ type testAPI struct {
 }
 
 func (ta *testAPI) mountListAndUnmountEncrypted(t *testing.T) {
+	log.Info("Starting mountListAndUnmountEncrypted test")
```
Comment (gbalint) [inline swarm/fuse/swarmfs_test.go]: Looks like a little too much for info level logging

Comment (holisticode) [reply swarm/fuse/swarmfs_test.go]: I respectfully disagree. Info is for high level info on what is going on. Error is just errors, and Warn of course warnings. So the next natural level to get an overview of what's going on is Info. Our code uses too much Debug level which makes it impossible to look for anything, and should use more the Trace level

Comment (nonsense) [reply swarm/fuse/swarmfs_test.go]: I also think that we don't need such `log.Info` before/after every test. The problem is that FUSE test suite is not coded according to conventions - we have one huge `TestFUSE` test, which calls all these subtests, which are not even related. We should just have a number of top-level `TestXXX` tests, where you can see the name of the tests being run, when you call `go test -v`.

The fact that we have too verbose `log.Debug` calls is another problem.

I don't have a strong opinion whether to keep the `log.Info`s or remove them right now, but we should probably refactor this whole test suite at some point.

Comment (nonsense) [reply swarm/fuse/swarmfs_test.go]: Furthermore it is very difficult to figure out which tests is deadlocking, I guess it is for this purpose that you added all these `log.Info`, so that it is visible in Travis? If this is the case, then I can totally understand, and we should leave them, until we have very high confidence that FUSE tests are not deadlocking.

File: swarm/fuse/swarmfs_test.go [hunk 8]
```diff
@@ -211,750 +248,1398 @@ type testAPI struct {
...
+	d := filepath.Join(root, name)
+	err := os.MkdirAll(d, 0777)
+	if err != nil {
+		return "", fmt.Errorf("Couldn't create dir inside test dir: %v", err)
+	}
+	return d, nil
+}
+
 func (ta *testAPI) mountListAndUnmountEncrypted(t *testing.T) {
+	log.Info("Starting mountListAndUnmountEncrypted test")
```
Comment (zelig) [inline swarm/fuse/swarmfs_test.go]: make these log lines at least debug

**Review by zelig — APPROVED** [review]

File: swarm/fuse/swarmfs_unix.go [hunk 9]
```diff
@@ -159,28 +161,59 @@ func (swarmfs *SwarmFS) Mount(mhash, mountpoint string) (*MountInfo, error) {
...
+	timer := time.NewTimer(mountTimeout)
 	// Check if the mount process has an error to report.
 	select {
-	case <-time.After(mountTimeout):
+	case <-timer.C:
 		fuse.Unmount(cleanedMountPoint)
 		return nil, errMountTimeout
-
 	case err := <-serverr:
 		fuse.Unmount(cleanedMountPoint)
```
Comment (zelig) [inline swarm/fuse/swarmfs_unix.go]: why no error check on `Unmount`?

File: swarm/fuse/swarmfs_unix.go [hunk 10]
```diff
@@ -159,28 +161,59 @@ func (swarmfs *SwarmFS) Mount(mhash, mountpoint string) (*MountInfo, error) {
...
+	   (caused in the bazil.org library and/or the SwarmRoot, SwarmDir and SwarmFile implementations)
+	*/
+	time.Sleep(2 * time.Second)
+
+	timer := time.NewTimer(mountTimeout)
 	// Check if the mount process has an error to report.
 	select {
-	case <-time.After(mountTimeout):
+	case <-timer.C:
 		fuse.Unmount(cleanedMountPoint)
```
Comment (zelig) [inline swarm/fuse/swarmfs_unix.go]: why no error check on Unmount?

File: swarm/fuse/swarmfs_unix.go [hunk 11]
```diff
@@ -159,28 +161,59 @@ func (swarmfs *SwarmFS) Mount(mhash, mountpoint string) (*MountInfo, error) {
...
+	   Workaround so far is to wait some time to give the OS enough time to initialize
+	   the fuse file system. During tests, this seemed to address the issue.
+
+	   HOWEVER IT SHOULD BE NOTED THAT THIS MAY ONLY BE AN EFFECT,
+	   AND THE DEADLOCK CAUSED BY SOMETHING ELSE BLOCKING ACCESS DUE TO SOME RACE CONDITION
+	   (caused in the bazil.org library and/or the SwarmRoot, SwarmDir and SwarmFile implementations)
+	*/
+	time.Sleep(2 * time.Second)
+
+	timer := time.NewTimer(mountTimeout)
```
Comment (zelig) [inline swarm/fuse/swarmfs_unix.go:195]: `defer timer.Stop()`?

File: swarm/fuse/swarmfs_test.go [hunk 12]
```diff
@@ -211,790 +251,1445 @@ type testAPI struct {
...
+	files         map[string]fileInfo
+	toEncrypt     bool
+	swarmfs       *SwarmFS
+}
+
+//create the root dir of a test
+func (ta *testAPI) initSubtest(name string) (*testData, error) {
+	var err error
+	d := &testData{}
+	d.testDir, err = ioutil.TempDir(os.TempDir(), name)
```
Comment (janos) [inline swarm/fuse/swarmfs_test.go:268]: `os.TempDir()` can be just an empty string `""`.

File: swarm/fuse/swarmfs_unix.go [hunk 13]
```diff
@@ -159,28 +161,59 @@ func (swarmfs *SwarmFS) Mount(mhash, mountpoint string) (*MountInfo, error) {
 	go func() {
 		log.Info("swarmfs", "serving hash", mhash, "at", cleanedMountPoint)
 		filesys := &SwarmRoot{root: rootDir}
+		//start serving the actual file system; see note below
 		if err := fs.Serve(fconn, filesys); err != nil {
 			log.Warn("swarmfs could not serve the requested hash", "error", err)
 			serverr <- err
 		}
-
+		mi.serveClose <- struct{}{}
```
Comment (janos) [inline swarm/fuse/swarmfs_unix.go:169]: This is ok only if there is one receiver for serveClose, which is the case here. If there are other places in the code that need to block until receiving from serveClose, then this needs to change to close(mi.serveClose).

File: swarm/fuse/swarmfs_test.go [hunk 14]
```diff
@@ -211,790 +251,1445 @@ type testAPI struct {
...
+	log.Debug("subtest terminated")
 }
 
 func (ta *testAPI) unmountWhenResourceBusyEncrypted(t *testing.T) {
+	log.Debug("Starting unmountWhenResourceBusyEncrypted test")
 	ta.unmountWhenResourceBusy(t, true)
+	log.Debug("Test unmountWhenResourceBusyEncrypted terminated")
 }
 func (ta *testAPI) unmountWhenResourceBusyNonEncrypted(t *testing.T) {
+	log.Debug("Starting unmountWhenResourceBusyNonEncrypted test")
```
Comment (janos) [inline swarm/fuse/swarmfs_test.go:577]: This test on macOS. Internal unmount https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/swarm/fuse/swarmfs_unix.go#L202 fails with an error unmount /var/folders/l4/tn9ytbgs5xx76lshwgx5bj1w0000gn/T/unmountWhenResourceBusy174427739/ex-mount1: resource busy, but there is a fallback strategy to use external unmount https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/swarm/fuse/swarmfs_util.go#L41 and in case of macOS, diskutil umount uses force option. This is a bit dangerous feature, as data may be lost in this case. There are workarounds for linux, to lazy unmount a fuse or ru use umount command instead of fusermount. But, if the "force" argument is removed from fuse.externalUnmount function, the test passes on macOS, too.

File: swarm/fuse/swarmfs_unix.go (hunk 13 above)
Comment (holisticode) [reply swarm/fuse/swarmfs_unix.go:169]: took the freedom to leave it as-is as there is only one place and probably will always be so, but thanks for pointing that out

File: swarm/fuse/swarmfs_unix.go (hunk 11 above)
Comment (holisticode) [reply swarm/fuse/swarmfs_unix.go:195]: fixed

File: swarm/fuse/swarmfs_unix.go (hunk 10 above)
Comment (holisticode) [reply swarm/fuse/swarmfs_unix.go]: fixed

File: swarm/fuse/swarmfs_unix.go (hunk 9 above)
Comment (holisticode) [reply swarm/fuse/swarmfs_unix.go]: fixed (we are already in error handling, but agreeing to let's be thorough)

File: swarm/fuse/swarmfs_unix.go (hunk 13 above)
Comment (janos) [reply swarm/fuse/swarmfs_unix.go:169]: Agreed.

**Review by janos — APPROVED** [review]
