### PR TITLE
swarm, swap: pass chequebook address at start-up

### LINKED ISSUE #1548: Users can provide deployed SWAP contract
# Problem
Right now each time Swarm is started with swap flag, new SWAP cheque contract is deployed.

# Task
- [ ] Add a flag that allows users to provide a SWAP contract address
- [ ] Programatically validate the provided contract
- [ ] If incorrect, raise fatal error
- [ ] If no such flag is provided, the contract address should be retrieved from the nodes storage. If does not exist the contract should still be automatically deployed.

### LINKED ISSUE #1599: On node startup, check the contract is already deployed
Currently, when we start up the node, we deploy the contract every time.

We need to check when we start the node if the contract has already been deployed, and if it has, not deploy again.

### PR DESCRIPTION
**Pull request by Eknir**
This PR aims to complete [1548](https://github.com/ethersphere/swarm/issues/1548) and the duplicate (?) [1599](https://github.com/ethersphere/swarm/issues/1599). 

No unit tests were provided, as this functionality resides largely in `swarm.Start`. Creating an integration test was attempted, but this is not possible with a simulated backend. 

To test manually (I used Rinkeby):
1) set `swap.AllowedNetworkID` to 4
2) ask me for some test ethers (if you don't have them) on the account which you use to start Swarm 
3) start Swarm without provided `chequebook`: 
`swarm --swap --swap-backend-url https://rinkeby.infura.io/v3/<INFURA_KEY>`
4) start Swarm with provided `chequebook`: `swarm --swap --swap-backend-url https://rinkeby.infura.io/v3/<INFURA_KEY>` --chequebook <Check the log from step 3>

An Infura key can be created by logging in at infura.io. I can give mine as well in PM.

With regards to [1599](https://github.com/ethersphere/swarm/issues/1599): it seems to me that it is suggested here that we have to store the chequebook to disk, such that it can be automatically re-used the next time a node boots up. I would propose to create a separate issue for this.

- closes https://github.com/ethersphere/swarm/issues/1548
- closes https://github.com/ethersphere/swarm/issues/1599

### CODE REVIEW

**Review by vojtechsimetka — APPROVED** [review]
Please consider my approval only as an information I saw it and it fulfils the issue description. I tried to run it the code looks good but I am no go expert :)

File: swap/swap.go [hunk 1]
```diff
@@ -542,7 +546,18 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
 	return contr.Issuer(nil)
 }
 
-// Deploy deploys the Swap contract
+// NewInstanceAt creates a new instance of the chequebook contract at address and sets chequebookAddr
```
Comment (ralph-pichler) [inline swap/swap.go]: I find this comment to be confusing. It doesn't really create a new instance of the contract but points to an existing one.

File: swarm.go [hunk 2]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
 	log.Info("Updated bzz local addr", "oaddr", fmt.Sprintf("%x", newaddr.OAddr), "uaddr", fmt.Sprintf("%s", newaddr.UAddr))
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
+			address := s.config.Contract
+			err := cswap.ValidateCode(context.Background(), s.backend, address)
```
Comment (ralph-pichler) [inline swarm.go]: I would recommend using this if style to be consistent with the rest of the codebase (same for the other 3 error checks):
```go
if err := cswap.ValidateCode(context.Background(), s.backend, address); err != nil {
	return fmt.Errorf("Provided address not a chequebook smart-contract: %v", err)
}
```

File: swap/swap.go (hunk 1 above)
Comment (mortelli) [reply swap/swap.go]: isn't it an instance on the go side? i.e. a new `struct`?

File: swarm.go [hunk 3]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
 	log.Info("Updated bzz local addr", "oaddr", fmt.Sprintf("%x", newaddr.OAddr), "uaddr", fmt.Sprintf("%s", newaddr.UAddr))
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
```
Comment (holisticode) [inline swarm.go]: no need for additional brackets here

File: swap/swap.go (hunk 1 above)
Comment (holisticode) [reply swap/swap.go]: I would rename this to `BindToContractAt` or something similar. It is indeed very confusing, as it is a method on `Swap`, and it is not creating a new instance of `Swap`, and, as @ralph-pichler says, not even a new contract.

The comment should be changed accordingly

Comment (Eknir) [reply swap/swap.go]: I agree about this being confusing. 
I propose to change it to:

`NewInstanceAt creates a new instance of an already existing chequebook contract at address and sets chequebookAddr`

What do you think?

File: swap/swap.go [hunk 4]
```diff
@@ -542,7 +546,18 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+func (s *Swap) NewInstanceAt(address common.Address, backend swap.Backend) error {
+	c, err := contract.InstanceAt(address, backend)
```
Comment (holisticode) [inline swap/swap.go]: why not right away
`s.contract, err`
No need for an intermediate variable

File: swarm.go (hunk 2 above)
Comment (Eknir) [reply swarm.go]: Done!

File: swap/swap.go [hunk 5]
```diff
@@ -532,6 +531,11 @@ func (s *Swap) verifyContract(ctx context.Context, address common.Address) error
 	return contract.ValidateCode(ctx, s.backend, address)
 }
 
+// SetChequebookAddr sets the chequebook address
+func (s *Swap) SetChequebookAddr(chequebookAddr common.Address) {
```
Comment (holisticode) [inline swap/swap.go]: Any reason why this needs to be exported?
It was `s.owner.Contract = <addr>`, thus it was not possible to set it from outside the package, now it would be. Not that I see a real security threat, but I'd like to know why you want to export it.

File: swarm.go [hunk 6]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
+			address := s.config.Contract
+			err := cswap.ValidateCode(context.Background(), s.backend, address)
+			if err != nil {
+				return fmt.Errorf("Provided address not a chequebook smart-contract: %v", err)
+			}
+			err = s.swap.NewInstanceAt(address, s.backend)
```
Comment (holisticode) [inline swarm.go]: same here

File: swap/swap.go [hunk 7]
```diff
@@ -127,12 +127,11 @@ func keyToID(key string, prefix string) enode.ID {
 }
 
 // createOwner assings keys and addresses
-func createOwner(prvkey *ecdsa.PrivateKey, contract common.Address) *Owner {
+func createOwner(prvkey *ecdsa.PrivateKey) *Owner {
 	pubkey := &prvkey.PublicKey
 	return &Owner{
```
Comment (mortelli) [inline swap/swap.go:132]: since we are already making changes to this function: could we go ahead and instantiate this `Owner` struct with its fields ordered in the same way as it is declared?

File: swap/swap.go (hunk 1 above)
Comment (Eknir) [reply swap/swap.go]: @mortelli , it is indeed *only* a new instance on the go-side.
To be precise:
```golang
type simpleContract struct {
	instance *contract.SimpleSwap
}
```
, which is implementing the `Contract interface`
```golang
type Contract interface {
	// SubmitChequeBeneficiary submits a cheque to a given beneficiary
	SubmitChequeBeneficiary(opts *bind.TransactOpts, backend Backend, serial *big.Int, amount *big.Int, timeout *big.Int, ownerSig []byte) (*types.Receipt, error)
	// CashChequeBeneficiary cashes the cheque by the beneficiary
	CashChequeBeneficiary(auth *bind.TransactOpts, backend Backend, beneficiary common.Address, requestPayout *big.Int) (*types.Receipt, error)
	// ContractParams returns contract info (e.g. deployed address)
	ContractParams() *Params
	// Issuer returns the contract owner from the blockchain
	Issuer(opts *bind.CallOpts) (common.Address, error)
	// Cheques returns the last cheque for the given address
	Cheques(opts *bind.CallOpts, addr common.Address) (*ChequeResult, error)
}
```
(see file `contracts/swap.go`).

File: swap/swap.go [hunk 8]
```diff
@@ -532,6 +531,11 @@ func (s *Swap) verifyContract(ctx context.Context, address common.Address) error
 	return contract.ValidateCode(ctx, s.backend, address)
 }
 
+// SetChequebookAddr sets the chequebook address
+func (s *Swap) SetChequebookAddr(chequebookAddr common.Address) {
+	s.owner.Contract = chequebookAddr
```
Comment (mortelli) [inline swap/swap.go:526]: i am assuming the reason for adding this function is either code clarity or extensibility. am i correct in doing so?

File: swarm.go [hunk 9]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
+			if err != nil {
+				return fmt.Errorf("Could not set the instance at provided cheqeubook: %v", err)
```
Comment (mortelli) [inline swarm.go]: typo in `chequebook`

File: swarm.go [hunk 10]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
+			address := s.config.Contract
+			err := cswap.ValidateCode(context.Background(), s.backend, address)
+			if err != nil {
+				return fmt.Errorf("Provided address not a chequebook smart-contract: %v", err)
```
Comment (holisticode) [inline swarm.go]: `err` could be returned due to two things:
* `CodeAt` failed
* `ErrNotASwapContract`

For the second case, the error formatting would not add information and would be redundant, for the first case it would be slightly misleading. I would change this to be 
`return fmt.Errorf("contract validation for %v failed: %v", address, err)`
or even just returning `return err`

File: swarm.go (hunk 9 above)
Comment (holisticode) [inline swarm.go]: just return `err`, no new information provided

File: swarm.go [hunk 11]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
+			}
+			err = s.swap.NewInstanceAt(address, s.backend)
+			if err != nil {
+				return fmt.Errorf("Could not set the instance at provided cheqeubook: %v", err)
+			}
+			log.Info("Using the provided chequebook", "chequebookAddr", address)
+		} else {
+			err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
+			if err != nil {
+				return fmt.Errorf("Unable to deploy swap contract: %v", err)
```
Comment (holisticode) [inline swarm.go]: same here, `err` already contains the text and actually has even been logged before

File: swap/swap.go (hunk 1 above)
Comment (mortelli) [reply swap/swap.go]: since the instance exists in the blockchain but not on the go side, maybe use `reference` instead of `instance`; it seems talking about instances is a half-truth.

@ralph-pichler any suggestions for a better comment? what do you think of @Eknir's proposal?

File: swarm.go [hunk 12]
```diff
@@ -374,11 +374,24 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
+			}
+			log.Info("SWAP contract deployed", "contract info", s.swap.DeploySuccess())
```
Comment (holisticode) [inline swarm.go]: Please add to the text "New" (so it reads "New SWAP contract deployed")

**Review by holisticode — CHANGES_REQUESTED** [review]
Very important PR, adds a pretty important functionality, thanks!

Please go through all the comments, mainly minor stuff about naming and go style

File: swarm.go [hunk 13]
```diff
@@ -374,11 +374,21 @@ func (s *Swarm) Start(srv *p2p.Server) error {
 	log.Info("Updated bzz local addr", "oaddr", fmt.Sprintf("%x", newaddr.OAddr), "uaddr", fmt.Sprintf("%s", newaddr.UAddr))
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
+			address := s.config.Contract
+			if err := cswap.ValidateCode(context.Background(), s.backend, address); err != nil {
+				return fmt.Errorf("Provided address not a chequebook smart-contract: %v", err)
```
Comment (mortelli) [inline swarm.go]: in case the `ValidateCode` call returns an error, there are 2 possibilities:
1. the operation of reading the code at this address can result in an error.
2. the bytecode doesn't match with what's expected—the resulting error string here would be: `Provided address not a chequebook smart-contract: not a swap contract`.

to avoid redundancy, i would suggest preceding the `err` text with something like `Error validating code at provided address:`

File: swap/swap.go (hunk 1 above)
Comment (holisticode) [reply swap/swap.go]: I would definitely not use `New`. `New` in go usually is used to create a new instance of the caller, not a new instance of some other object.

Maybe `BindToReferenceAt` or `BindToContractAt`, `ContractAt` but not `New...`

File: swarm.go [hunk 14]
```diff
@@ -374,11 +374,21 @@ func (s *Swarm) Start(srv *p2p.Server) error {
 	log.Info("Updated bzz local addr", "oaddr", fmt.Sprintf("%x", newaddr.OAddr), "uaddr", fmt.Sprintf("%s", newaddr.UAddr))
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
+			address := s.config.Contract
+			if err := cswap.ValidateCode(context.Background(), s.backend, address); err != nil {
```
Comment (mortelli) [inline swarm.go]: shouldn't we call `verifyContract` instead of `ValidateCode` directly?

File: swap/swap.go [hunk 15]
```diff
@@ -542,7 +546,18 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
 	return contr.Issuer(nil)
 }
 
-// Deploy deploys the Swap contract
+// NewInstanceAt creates a new instance of an already existing chequebook contract at address and sets chequebookAddr
+func (s *Swap) NewInstanceAt(address common.Address, backend swap.Backend) error {
```
Comment (mortelli) [inline swap/swap.go]: i am not going to ask you to change the name here (you know my position on this :stuck_out_tongue: ) but i _will_ say that i find it a bit weird that we have a function named `NewInstanceAt` which itself calls _another_ function called `InstanceAt`.

**Review by mortelli — CHANGES_REQUESTED** [review]
in broad terms this PR looks good to me :+1: 

i have made a few minor comments/corrections and left a couple of questions. i am happy to approve once these are resolved.

besides this, please:
- rebase/merge this with `master`.
- update the name of the PR to reflect the affected packages.

finally, a disclaimer: i have not run the manual tests myself.

File: swarm.go (hunk 10 above)
Comment (mortelli) [reply swarm.go]: can i just express how scary it is that we made almost _the exact same_ comment? :fearful:

File: swap/swap.go (hunk 1 above)
Comment (Eknir) [reply swap/swap.go]: Changed the function to `ContractAt` and updated the documentation to:
```
//ContractAt binds to an instance of an already existing chequebook contract at address and sets chequebookAddr
```

File: swap/swap.go (hunk 7 above)
Comment (Eknir) [reply swap/swap.go:132]: Will do!

File: swap/swap.go (hunk 8 above)
Comment (Eknir) [reply swap/swap.go:526]: Only for code clarity indeed. This function is actually redundant as the chequebookAddress is already implicitly set as part of the contract instance at `swap.contract` (from there you can make direct calls to the smart-contract, so it must be set). Nevertheless, the contract address is not publicly exposed in `swap.contract`, so we need some refactor and rewrite.

File: swarm.go (hunk 9 above)
Comment (Eknir) [reply swarm.go]: Good catch!

File: swap/swap.go (hunk 4 above)
Comment (Eknir) [reply swap/swap.go]: Done

File: swap/swap.go (hunk 5 above)
Comment (Eknir) [reply swap/swap.go]: Please attribute this to my relative inexperience with Golang. With hindsight, it is indeed not needed to export it. Why I thought differently when I made this change: no idea anymore. Thanks for the catch!

File: swarm.go (hunk 3 above)
Comment (Eknir) [reply swarm.go]: Actually, this seems to be needed.
If I don't have brackets it complains at the opening bracket:
`syntax error: unexpected { at end of statement` and the else branch:
`syntax error: unexpected else after top level declaration`
I adopted this style from line `swarm.go:302`
```golang
if addr != (common.Address{}) {
```
which indeed resolves the error.

File: swarm.go (hunk 12 above)
Comment (Eknir) [reply swarm.go]: done

File: swarm.go (hunk 11 above)
Comment (Eknir) [reply swarm.go]: done

File: swarm.go (hunk 13 above)
Comment (Eknir) [reply swarm.go]: Indeed scarily similar to the comment by @holisticode ... Resolved!

File: swarm.go (hunk 14 above)
Comment (Eknir) [reply swarm.go]: Nice one. Indeed that would be better!

Comment (Eknir) [reply swarm.go]: With hindsight, I would actually propose to not change it to `ValidateCode`. The reason is that `verifyContract` is used as part of `protocol.go` to verify the chequebook contract of the counterparty. @ralph-pichler is doing research on how to make this check more elaborate. 
In the instance where I am using the check, however, we actually only have to verify the `deployedBytecode`, so I would prefer to use the lower level call (`cswap.validateCode`) over the higher-level call (`swap.verifyContract`) which might add more checks in the future.

File: swap/swap.go (hunk 15 above)
Comment (Eknir) [reply swap/swap.go]: Changed it to be just `InstanceAt`

File: swap/swap.go (hunk 1 above)
Comment (Eknir) [reply swap/swap.go]: Final resolution: as this call is deferring to `contract.InstanceAt`, I see no reason why we would name it anything other than that. 
Hence, I decided to change it to:
```golang
// InstanceAt creates a new instance of an already existing chequebook contract at address and sets chequebookAddr
func (s *Swap) InstanceAt(address common.Address, backend swap.Backend) (err error) {
	s.contract, err = contract.InstanceAt(address, backend)
	if err != nil {
		return err
	}
	s.setChequebookAddr(address)
	return nil
}
```
@holisticode , tagging you, as you already gave a thumbs-up on my previous proposed solution to make it `ContractAt`

**Review by holisticode — APPROVED** [review]

File: swarm.go (hunk 14 above)
Comment (mortelli) [reply swarm.go]: while i see your point, i think changes like these should be made in an atomic manner—i'm not a fan of leaving code around due to "_just in case_"- or "_for later use_"-type of situations.

right now, all `verifyContract` does is call `ValidateCode`. even their comments are very similar:
```
// verifyContract checks if the bytecode found at address matches the expected bytecode
```
```
// ValidateCode checks that the on-chain code at address matches the expected swap
// contract code.
```
i would either: 
1. remove `ValidateCode` and always call `verifyContract` directly
2. always call `ValidateCode` for consistency's sake

i will not consider this a blocker for approval, though :+1:

File: swap/swap.go (hunk 8 above)
Comment (mortelli) [reply swap/swap.go:526]: relevant issue: #1728. resolving

**Review by mortelli — APPROVED** [review]

File: swap/swap.go [hunk 16]
```diff
@@ -537,7 +541,17 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+	s.contract, err = contract.InstanceAt(address, backend)
+	if err != nil {
+		return err
+	}
+	s.setChequebookAddr(address)
+	return nil
+}
+
+// Deploy deploys the Swap contract and sets the contract address
 func (s *Swap) Deploy(ctx context.Context, backend swap.Backend, path string) error {
```
Comment (santicomp2014) [inline swap/swap.go]: I'm confused as to what the path parameter does.
Is this to satisfy a Interface?, or is it something that is not being used.

And if this is the case what would be the use of such path.

File: swarm.go [hunk 17]
```diff
@@ -374,11 +374,21 @@ func (s *Swarm) Start(srv *p2p.Server) error {
 	log.Info("Updated bzz local addr", "oaddr", fmt.Sprintf("%x", newaddr.OAddr), "uaddr", fmt.Sprintf("%s", newaddr.UAddr))
 
 	if s.config.SwapEnabled {
-		err := s.swap.Deploy(context.Background(), s.backend, s.config.Path)
-		if err != nil {
-			return fmt.Errorf("Unable to deploy swap contract: %v", err)
+		if s.config.Contract != (common.Address{}) {
```
Comment (zelig) [inline swarm.go]: I think it would be nicer to extract this into a setup function. too much swap specific logic is here and makes swarm.go harder to read.

Comment (zelig) [reply swarm.go]: then you can also eliminate the else-s as you just return

**Review by zelig — COMMENTED** [review]
minor: please extract chequebook contract setup into the swap package to keep swarm.go setup lean.

File: swap/swap.go (hunk 16 above)
Comment (Eknir) [reply swap/swap.go]: I am confused about this as well. Actually removed it before when I was doing refactoring, but when I reverted the refactoring, I also left this one in now. 
Tagging @holisticode , maybe he knows. I would personally remove it, as it does not seem to have a purpose

File: swarm.go (hunk 14 above)
Comment (Eknir) [reply swarm.go]: Choose for option 2. 
Meant I also had to rewrite some tests:
`TestVerifyContract` => `TestValidateCode`
`TestVerifyWrongContract` => `TestValideWrongCode`
I don't find this particularly nice, as the unit tests in `swap` are now actually testing functionality of `contracts/swap`. If we would like to change this, however, there is a need to create a new testSuite in `contracts/swap`. 

I refrain from doing this at the moment but will put it on the agenda for the next sync meeting to hear to the opinion of team members.

File: swarm.go (hunk 17 above)
Comment (Eknir) [reply swarm.go]: Done!

Comment (Eknir) [reply swarm.go]: @zelig , can you confirm I handled this comment as you intended?

File: swap/swap.go (hunk 16 above)
Comment (mortelli) [reply swap/swap.go]: if the tests pass after removing this parameter, i say let's go ahead with this change

File: swarm.go (hunk 14 above)
Comment (mortelli) [reply swarm.go]: thank you for putting this down for discussion. 

i'm all for a new test suite if the situation calls for it :+1:

File: swap/swap.go [hunk 18]
```diff
@@ -537,8 +536,38 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+
+// BindToContractAt binds an instance of an already existing chequebook contract at address and sets chequebookAddr
+func (s *Swap) BindToContractAt(address common.Address) (err error) {
+
+	if err := contract.ValidateCode(context.Background(), s.backend, address); err != nil {
+		return fmt.Errorf("contract validation for %v failed: %v", address, err)
+	}
+	s.contract, err = contract.InstanceAt(address, s.backend)
+	if err != nil {
+		return err
```
Comment (mortelli) [inline swap/swap.go:563]: since `err` is implicitly initialized, you can just `return` here

File: swap/swap.go [hunk 19]
```diff
@@ -537,8 +536,38 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+	}
+	s.setChequebookAddr(address)
+	return nil
```
Comment (mortelli) [inline swap/swap.go:566]: same here

File: swap/swap.go [hunk 20]
```diff
@@ -537,8 +536,38 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
 	return contr.Issuer(nil)
 }
 
-// Deploy deploys the Swap contract
-func (s *Swap) Deploy(ctx context.Context, backend swap.Backend, path string) error {
+// StartChequebook deploys a new instance of a chequebook if chequebookAddr is empty, otherwise it wil bind to an existing instance
+func (s *Swap) StartChequebook(chequebookAddr common.Address) (err error) {
+	if chequebookAddr != (common.Address{}) {
+		if err := s.BindToContractAt(chequebookAddr); err != nil {
+			return err
```
Comment (mortelli) [inline swap/swap.go:543]: since `err` is implicitly initialized, you can just `return` here

File: swap/swap.go [hunk 21]
```diff
@@ -537,8 +536,38 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+		}
+		log.Info("Using the provided chequebook", "chequebookAddr", chequebookAddr)
+	} else {
+		if err := s.Deploy(context.Background(), s.backend); err != nil {
+			return err
```
Comment (mortelli) [inline swap/swap.go:548]: `return`

File: swap/swap.go [hunk 22]
```diff
@@ -537,8 +536,38 @@ func (s *Swap) getContractOwner(ctx context.Context, address common.Address) (co
...
+		}
+		log.Info("New SWAP contract deployed", "contract info", s.DeploySuccess())
+	}
+	return nil
```
Comment (mortelli) [inline swap/swap.go:552]: `return` or declare the function return as `error` instead of `err error`

**Review by mortelli — COMMENTED** [review]
i am keeping my approval review, but i have made some additional (minor) comments.

be sure to run the linter, the test suite, and `rebase`/`merge` with `master` to have this ready to merge after any change.

**Review by santicomp2014 — APPROVED** [review]
The PR [#1720](https://github.com/ethersphere/swarm/pull/1720) will be affected by these changes.
I will wait until you get the PR Accepted, so I can pull these changes and continue with my PR.

LGTM.

File: swap/swap.go (hunk 22 above)
Comment (zelig) [reply swap/swap.go:552]: yes get rid of named return value here

File: swap/swap.go (hunk 18 above)
Comment (zelig) [reply swap/swap.go:563]: get rid of named paramater. 
@mortelli our code policy is to write return arguments explicitly even if we have named return params

File: swarm.go [hunk 23]
```diff
@@ -374,21 +374,7 @@ func (s *Swarm) Start(srv *p2p.Server) error {
...
-				return err
-			}
-			log.Info("Using the provided chequebook", "chequebookAddr", address)
-		} else {
-			if err := s.swap.Deploy(context.Background(), s.backend, s.config.Path); err != nil {
-				return err
-			}
-			log.Info("New SWAP contract deployed", "contract info", s.swap.DeploySuccess())
-		}
+		s.swap.StartChequebook(s.config.Contract)
```
Comment (zelig) [inline swarm.go]: oops, you swallow the error returned here.

**Review by zelig — CHANGES_REQUESTED** [review]

File: swap/swap.go (hunk 18 above)
Comment (Eknir) [reply swap/swap.go:563]: I would like to keep the initialization of `err` in the function initialization, because otherwise, I can't do 
```golang
s.contract, err = contract.InstanceAt(address, s.backend)
```
Obviously, if it is a strict policy not to have named return parameters, I can do that, but in this case, I need 2 extra lines of code (to initialize a variable for the `contractInstance`, and assign this to `s.contract`). This was how I did it initially, but @holisticode asked me to do it in a one-liner.

File: swarm.go (hunk 23 above)
Comment (Eknir) [reply swarm.go]: Oops, I'll throw it out again!

File: swap/swap.go (hunk 22 above)
Comment (Eknir) [reply swap/swap.go:552]: Got rit of named return

File: swap/swap.go (hunk 21 above)
Comment (Eknir) [reply swap/swap.go:548]: I won't change this, due to Swarm code policy. Please tell me if you disagree.

File: swap/swap.go (hunk 20 above)
Comment (Eknir) [reply swap/swap.go:543]: I won't change this, due to Swarm code policy. Please tell me if you disagree.

File: swap/swap.go (hunk 19 above)
Comment (Eknir) [reply swap/swap.go:566]: I won't change this, due to Swarm code policy. Please tell me if you disagree.

File: swap/swap.go (hunk 18 above)
Comment (zelig) [reply swap/swap.go:563]: this is fine. I also like sometimes that vars are initialised,
 the policy is more about not having bare `return`-s if the function has return values. 
it makes things more readable

**Review by zelig — APPROVED** [review]
