### PR TITLE
swap: fixed bug which needs cheques to be confirmed

### LINKED ISSUE #1933: Update swap simulation tests for pending cheques
`waitForChequeProcessed` needs to be adapted to also wait for the cheque to be confirmed (waiting for `cashDone` is no longer necessary). Currently a new cheque is attempted to be sent while the old one is not confirmed yet, leading to the pending cheque to be resent, but waitForChequeProcessed is waiting for a new cheque causing the test to hang and timeout.

```
=== RUN   TestMultiChequeSimulation
WARN [11-05|13:11:24.556|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=0e0000…947e6f
WARN [11-05|13:11:24.571|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=568d95…ff9a5c
WARN [11-05|13:11:24.581|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=37e346…6cc0f7
WARN [11-05|13:11:24.596|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=918b39…83cdd2
WARN [11-05|13:11:24.608|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=ce0e24…413c86
WARN [11-05|13:11:24.620|github.com/ethersphere/swarm/swap/swap.go:450]              cheque bounced                           swaplog=* base=a5126ccf56b605e7 tx=18146b…4133c6
WARN [11-05|13:11:24.621|github.com/ethersphere/swarm/swap/swap.go:353]              cheque sent by peer has already been received in the past swaplog=* base=d9b5d8bd215a7f98 peer=bb40ff67e0811dfa cumulativePayout=176699531344266
WARN [11-05|13:11:24.621|github.com/ethersphere/swarm/swap/swap.go:415]              ignoring confirm msg, no pending cheque  swaplog=* base=d9b5d8bd215a7f98 peer=4ac7527c49bc60c6 confirm message cheque="Contract: 6c60ee4660ee385f658345b6bed000b513757ff4 Beneficiary: 467bcb061b0199d906a306874500cd796d119ebf CumulativePayout: 176699531344266 Honey: 19633281260474"
ERROR[11-05|13:11:24.981|accounts/usbwallet/hub.go:170]                              Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-05|13:11:24.981|accounts/usbwallet/hub.go:170]                              Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-05|13:11:24.981|accounts/usbwallet/hub.go:170]                              Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[11-05|13:11:44.622|github.com/ethersphere/swarm/p2p/protocols/protocol.go:249] dropping peer with DiscSubprotocolError  peer=4ac7527c49bc60c6 reason="hive stopping"
--- FAIL: TestMultiChequeSimulation (20.15s)
    simulations_test.go:430: timed out waiting for cheque to be processed
```

### PR DESCRIPTION
**Pull request by holisticode**
This PR fixes a bug in simulation tests for swap, where sometimes, due to timing issues, the test may hang because a new cheque arrives and the old one is not confirmed yet.

Fixes https://github.com/ethersphere/swarm/issues/1933

### CODE REVIEW

File: swap/simulations_test.go [hunk 1]
```diff
@@ -676,33 +682,60 @@ func TestBasicSwapSimulation(t *testing.T) {
...
-		backend := ts.swap.backend.(*swapTestBackend)
-		select {
-		case <-ctx.Done():
-			t.Fatal("timed out waiting for cheque to be processed")
-		case <-backend.cashDone:
-			wg.Done()
+		for {
+			select {
+			case <-ctx.Done():
+				err = errors.New("Timed out waiting for cheque to have been cashed")
```
Comment (ralph-pichler) [inline swap/simulations_test.go]: I wonder what happens if multiple of those waiting functions time out. `err` gets written to multiple times and we get the error of the last go routine to finish? I wonder if it would make sense to log the errors here, so in case the test fails we see all the things that went wrong at once instead of just the "last" error.

Comment (holisticode) [reply swap/simulations_test.go]: Yes, good point, because really if it fails it doesn't matter that much, but to be able to fix the issue we should know the one which failed.

File: swap/simulations_test.go [hunk 2]
```diff
@@ -325,18 +327,20 @@ func TestPingPongChequeSimulation(t *testing.T) {
...
 				t.Fatal(err)
 			}
-			if err := waitForChequeProcessed(t, ts2, counter, lastCount); err != nil {
+			if err := waitForChequeProcessed(t, params.backend, counter, lastCount, ts1.swap.peers[p2], expectedPayout1); err != nil {
 				t.Fatal(err)
 			}
 			lastCount += 1
+			expectedPayout1 += DefaultPaymentThreshold + 1
 		} else {
 			if err := p1Peer.Send(context.Background(), &testMsgBigPrice{}); err != nil {
```
Comment (ralph-pichler) [inline swap/simulations_test.go:339]: In one test run (out of 1000) I got a nil pointer in this line:
```
   --- FAIL: TestPingPongChequeSimulation (0.08s)
   panic: runtime error: invalid memory address or nil pointer dereference [recovered]
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc52f37]
       
   goroutine 36 [running]:
   testing.tRunner.func1(0xc0004b5300)
   	/usr/local/go/src/testing/testing.go:874 +0x3a3
   panic(0xd84600, 0x16a17b0)
   	/usr/local/go/src/runtime/panic.go:679 +0x1b2
   github.com/ethersphere/swarm/swap.TestPingPongChequeSimulation(0xc0004b5300)
   	/home/user/swarm/swap/simulations_test.go:336 +0x927
   testing.tRunner(0xc0004b5300, 0xf3c3f0)
   	/usr/local/go/src/testing/testing.go:909 +0xc9
   created by testing.(*T).Run
   	/usr/local/go/src/testing/testing.go:960 +0x350
   FAIL	github.com/ethersphere/swarm/swap	0.161s
   FAIL
```

Comment (holisticode) [reply swap/simulations_test.go:339]: Hmmm that's a hell of a difficult one. but I also wonder how many tests in the entire code base would stand the check of 1000 runs. It never happened before in many high count runs...

Comment (ralph-pichler) [reply swap/simulations_test.go:339]: From what I see the only thing that could be `nil` here is `p1Peer` (which should not be nil because we wait for swap connections to be established). Maybe the protocol got disconnected inbetween the waiting loop and `p1Peer := ts2.peers[p1] `. Either way if it doesn't happen again we can probably ignore this. Also very unlikely that this is related to the changes from this PR.

**Review by ralph-pichler — APPROVED** [review]
There are still other issues happening in the tests sometimes but they seem to be unrelated to the changes in this PR. The pending cheque bug appears to be fixed.

File: swap/simulations_test.go (hunk 2 above)
Comment (janos) [reply swap/simulations_test.go:339]: One thing that may be related to this is that there are two maps of peers in this test. One is `testService.peers` and another `testService.swap.peers`. The panic is on the peer from the first one but the for loop is checking for the second one if it contains at least one peer. I think that it would be more correct to wait for the first peers map:

```go
		ts1.lock.Lock()
		ts1Len = len(ts1.peers)
		ts1.lock.Unlock()

		ts2.lock.Lock()
		ts2Len = len(ts2.peers)
		ts2.lock.Unlock()
```

This may fix this issue as the nil peer can happen if the map does not contain it. But I did not manage to confirm that.

File: swap/simulations_test.go [hunk 3]
```diff
@@ -676,33 +683,60 @@ func TestBasicSwapSimulation(t *testing.T) {
...
 	defer cancel()
 
 	// we are going to wait for two things:
-	// * that a cheque has been processed
+	// * that a cheque has been processed and confirmed
 	// * that the other side actually did process the testMsgPrice message
 	//   (by checking that the message counter has been increased)
 	var wg sync.WaitGroup
-	wg.Add(2)
+	errs := []string{}
```
Comment (janos) [inline swap/simulations_test.go:699]: This slice may be changed in three different goroutines. It is possible to have a data race on it. That can cause to miss some errors, even in this case it does not matter so much. I think that it should be protected to have the correct code.

File: swap/simulations_test.go [hunk 4]
```diff
@@ -676,33 +683,60 @@ func TestBasicSwapSimulation(t *testing.T) {
...
+				wg.Done()
+				return
+			case <-backend.cashDone:
+				wg.Done()
+				return
+			}
+		}
+	}()
+
+	go func() {
```
Comment (janos) [inline swap/simulations_test.go:718]: This goroutine creates a data race. It can be solved by setting lock on Peer around getLastSentCumulativePayout a few lines below.

```
ARNING: DATA RACE
Write at 0x00c0120eefd8 by goroutine 144:
  github.com/ethersphere/swarm/swap.(*Peer).setLastSentCheque()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/peer.go:105 +0x5e
  github.com/ethersphere/swarm/swap.(*Swap).handleConfirmChequeMsg()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/swap.go:424 +0x171

Previous read at 0x00c0120eefd8 by goroutine 142:
  github.com/ethersphere/swarm/swap.waitForChequeProcessed.func2()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/peer.go:86 +0x87

Goroutine 144 (running) created at:
  github.com/ethersphere/swarm/swap.(*Swap).handleMsg.func1()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/swap.go:335 +0xdc
  github.com/ethersphere/swarm/p2p/protocols.(*Peer).handleIncoming()
      /Users/janos/go/src/github.com/ethersphere/swarm/p2p/protocols/protocol.go:338 +0xc2d
  github.com/ethersphere/swarm/p2p/protocols.(*Peer).Run()
      /Users/janos/go/src/github.com/ethersphere/swarm/p2p/protocols/protocol.go:235 +0x4c
  github.com/ethersphere/swarm/swap.(*Swap).run()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/protocol.go:131 +0x5bb
  github.com/ethersphere/swarm/swap.(*Swap).run-fm()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/protocol.go:105 +0x63
  github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1()
      /Users/janos/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.2/p2p/peer.go:363 +0x8d

Goroutine 142 (running) created at:
  github.com/ethersphere/swarm/swap.waitForChequeProcessed()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/simulations_test.go:713 +0x23c
  github.com/ethersphere/swarm/swap.TestMultiChequeSimulation()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/simulations_test.go:460 +0xb2a
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x284
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1217 +0x382
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db_util.go:52 +0x2f8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:130 +0x9f0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x284
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1217 +0x382
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:476 +0xc5
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:125 +0x9cc
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:197 +0x1d3
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/session.go:134 +0xf4
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/session.go:142 +0x1938
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:183 +0xf8
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:219 +0xa5
  github.com/ethersphere/swarm/swap.newSharedBackendSwaps()
      /Users/janos/go/src/github.com/ethersphere/swarm/state/dbstore.go:49 +0x723
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x284
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1217 +0x382
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db_util.go:52 +0x2f8
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:130 +0x9f0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x284
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1217 +0x382
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:476 +0xc5
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:125 +0x9cc
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:197 +0x1d3
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xcf
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /usr/local/go/src/fmt/scan.go:114 +0x192
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/storage/file_storage.go:458 +0x2c4
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/session.go:134 +0xf4
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/session.go:142 +0x1938
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:183 +0xf8
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/janos/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20190318030020-c3a204f8e965/leveldb/db.go:219 +0xa5
  github.com/ethersphere/swarm/swap.newSharedBackendSwaps()
      /Users/janos/go/src/github.com/ethersphere/swarm/state/dbstore.go:49 +0x723
  github.com/ethersphere/swarm/swap.TestMultiChequeSimulation()
      /Users/janos/go/src/github.com/ethersphere/swarm/swap/simulations_test.go:376 +0x5c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
==================
```

**Review by janos — CHANGES_REQUESTED** [review]
Thanks for solving the issue. I can confirm that it is fixed by running test in the environment where failures happened frequently.

I have some comments related to data races, which should be easy to fix.

File: swap/simulations_test.go (hunk 2 above)
Comment (holisticode) [reply swap/simulations_test.go:339]: The reason why we wait for the 2nd map is that we only can know that we have all connections established when the 2nd map has the expected amount of connections, otherwise when sending cheques we may not know if the peer is there already.

So maybe the real thing is to wait for both. I am thinking that we could to that under the same lock,,,I will do some trial but if it doesn't work well I will leave it as-is.

**Comment by holisticode** [comment]
Thanks @janos for catching those races. I made fixes.

**Review by janos — APPROVED** [review]
Thanks, LGTM.
