### PR TITLE
bzzeth: protocol runloop now quits on peer disconnect

### LINKED ISSUE #1730: swarm node doesn't reconnect to peers correctly after restart
After a node established peers when it joins the network, if it is restarted, for some reason it doesn't correctly re-establish connections with known peers.

It is not clear why this is happening, and definitely not due to the `maxpeers` setting, as peers have much fewer peers than their `maxpeers` limit.

Screenshot 2019-09-05 at 17 08 07

In screenshot, at the top we see a node's connectivity when it is first started and it has established connections to its peers.

In the bottom screen we see its connectivity after reboot - it fails to connect with some of its closest peers.

### PR DESCRIPTION
**Pull request by jmozah**
fixes #1730

### CODE REVIEW

File: bzzeth/bzzeth.go [hunk 1]
```diff
@@ -85,6 +90,15 @@ func (b *BzzEth) handleMsg(p *Peer) func(context.Context, interface{}) error {
 	}
 }
 
+// handleMsgFromSwarmNode is used in the case if this node is connected to a Swarm node
+// If any message is received in this case, the peer needs to be dropped
+func (b *BzzEth) handleMsgFromSwarmNode(p *Peer) func(context.Context, interface{}) error {
+	return func(ctx context.Context, msg interface{}) error {
+		p.logger.Debug("bzzeth.handleMsgFromSwarmNode")
+		return errRcvdMsgFromSwarmNode
```
Comment (janos) [inline bzzeth/bzzeth.go:98]: Is it needed to always return this error?

File: bzzeth/wire.go [hunk 2]
```diff
@@ -25,6 +25,7 @@ var Spec = &protocols.Spec{
 	MaxMsgSize: 10 * 1024 * 1024,
 	Messages: []interface{}{
 		Handshake{},
+		DummyMessage{},
```
Comment (janos) [inline bzzeth/wire.go]: I suppose that this message is here for testing until the protocol is finalized?

File: bzzeth/bzzeth_test.go [hunk 3]
```diff
@@ -141,17 +156,18 @@ func TestBzzBzzHandshake(t *testing.T) {
...
 	}
 
-	// after handshake expect protocol to hang, peer not added to pool
-	p := b.peers.get(node.ID())
-	if p != nil {
-		t.Fatal("bzzeth swarm peer incorrectly added")
+	// Wait for sometime and see if peer is connected and idling
+	time.Sleep(1000 * time.Millisecond)
+	if _, ok := b.peers.peers[node.ID()]; !ok {
+		t.Fatalf("peer is not connected")
```
Comment (janos) [inline bzzeth/bzzeth_test.go]: [This test](https://travis-ci.org/ethersphere/swarm/jobs/583721259#L661) seems flaky now:

```
ERROR[09-11|15:53:03.329|github.com/ethersphere/swarm/p2p/protocols/protocol.go:238] peer.handleIncoming                      err="Message handler error: (msg code 1): received message from Swarm node"
--- FAIL: TestBzzBzzHandshake (1.09s)
    bzzeth_test.go:162: peer still connected
FAIL
coverage: 46.0% of statements
FAIL	github.com/ethersphere/swarm/bzzeth	2.364s
```

File: bzzeth/bzzeth.go (hunk 1 above)
Comment (zelig) [reply bzzeth/bzzeth.go:98]: yes. no protocol message is legal from another swarm node at this point

File: bzzeth/bzzeth.go [hunk 4]
```diff
@@ -85,6 +90,15 @@ func (b *BzzEth) handleMsg(p *Peer) func(context.Context, interface{}) error {
 	}
 }
 
+// handleMsgFromSwarmNode is used in the case if this node is connected to a Swarm node
+// If any message is received in this case, the peer needs to be dropped
+func (b *BzzEth) handleMsgFromSwarmNode(p *Peer) func(context.Context, interface{}) error {
+	return func(ctx context.Context, msg interface{}) error {
+		p.logger.Debug("bzzeth.handleMsgFromSwarmNode")
```
Comment (zelig) [inline bzzeth/bzzeth.go]: this can be `Warn` i think

File: bzzeth/wire.go [hunk 5]
```diff
@@ -33,3 +34,9 @@ var Spec = &protocols.Spec{
 type Handshake struct {
 	ServeHeaders bool // indicates if this node is expected to serve requests for headers
 }
+
+// Dummy message to send from another Swarm node
```
Comment (zelig) [inline bzzeth/wire.go]: we must  not introduce another message, just use the Handshake

We need to test if the protocol returns when 
- a message is sent (currently in this PR it is only the Handshake message)
- the peer disconnects 

I think we should test both.

**Review by zelig — CHANGES_REQUESTED** [review]

File: bzzeth/wire.go (hunk 2 above)
Comment (jmozah) [reply bzzeth/wire.go]: yes

File: bzzeth/bzzeth_test.go (hunk 3 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go]: I added some delay after sending the dummy message... It should work fine now.

File: bzzeth/bzzeth.go (hunk 4 above)
Comment (jmozah) [reply bzzeth/bzzeth.go]: Done

**Review by zelig — CHANGES_REQUESTED** [review]

File: bzzeth/bzzeth_test.go [hunk 6]
```diff
@@ -97,19 +114,11 @@ func TestBzzEthHandshake(t *testing.T) {
...
-	// after successful handshake, expect peer added to peer pool
-	var p *Peer
-	for i := 0; i < 10; i++ {
-		p = b.peers.get(node.ID())
-		if p != nil {
-			break
-		}
-		time.Sleep(100 * time.Millisecond)
-	}
+	time.Sleep(100 * time.Millisecond)
```
Comment (janos) [inline bzzeth/bzzeth_test.go]: Are we ok with synchronizations with sleeps?

File: bzzeth/bzzeth_test.go [hunk 7]
```diff
@@ -121,37 +130,39 @@ func TestBzzEthHandshake(t *testing.T) {
 	}
 }
 
-// TestBzzBzzHandshake tests that a handshake between two Swarm nodes
-func TestBzzBzzHandshake(t *testing.T) {
+// TestBzzBzzHandshakeWithMessage tests that a handshake between two Swarm nodes and message exchange
+// disconnects the peer
+func TestBzzBzzHandshakeWithMessage(t *testing.T) {
+	// redefine isSwarmNodeFunc to force recognise remote peer as swarm node
+	isSwarmNodeFunc = func(_ *Peer) bool { return true }
```
Comment (janos) [inline bzzeth/bzzeth_test.go:174]: Should isSwarmNodeFunc be reset to the original value after the test is done?

File: bzzeth/bzzeth_test.go (hunk 3 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go]: Pushed it now

Comment (jmozah) [reply bzzeth/bzzeth_test.go]: Sleep seems to be the option for now...

File: bzzeth/bzzeth_test.go (hunk 7 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go:174]: Can be reset. But i don't see the need as we create a new BZZ service for every testcase.

File: bzzeth/bzzeth_test.go (hunk 6 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go]: How do you suggest we test this otherwise?

Comment (janos) [reply bzzeth/bzzeth_test.go]: With other synchronization methods, like we do in other tests. Sometimes with hooks, or events or, at least have a retry function that periodically checks for the expected condition. Sleeps are easy to do, but they are creating flaky tests where scheduler does not schedule what is expected in the expected sleep time.

File: bzzeth/bzzeth_test.go (hunk 7 above)
Comment (janos) [reply bzzeth/bzzeth_test.go:174]: I see that you removed the reset in this PR. Regardless of the purpose, if something global is changed it is polite to revert it back when the test is finished with it. What would happen if another test is made that relies implicitly on default value of isSwarmNodeFunc? The order of test functions would matter as no test function could rely what is the value of isSwarmNodeFunc.

File: bzzeth/bzzeth_test.go (hunk 3 above)
Comment (janos) [reply bzzeth/bzzeth_test.go]: I would like to hear other opinions on using sleeps.

**Review by janos — APPROVED** [review]

File: bzzeth/bzzeth_test.go [hunk 8]
```diff
@@ -123,35 +139,94 @@ func TestBzzEthHandshake(t *testing.T) {
...
-	err = tester.TestDisconnected(&p2ptest.Disconnect{Peer: node.ID(), Error: errors.New("protocol returned")})
+	// Send a dummy handshake message, wait for sometime and check if peer is dropped
+	err = dummyHandshakeMessage(tester, node.ID())
 	if err != nil {
 		t.Fatal(err)
 	}
-
+	// after successful handshake, expect peer added to peer pool
+	var p1 *Peer
+	for i := 0; i < 10; i++ {
```
Comment (janos) [inline bzzeth/bzzeth_test.go:214]: This code is pasted three times in this file. It would be nice to have it in a function. As this package will be changed in the near future, it is ok to address this later.

File: bzzeth/bzzeth_test.go [hunk 9]
```diff
@@ -123,35 +139,94 @@ func TestBzzEthHandshake(t *testing.T) {
...
+		p1 = b.peers.get(node.ID())
+		if p1 != nil {
```
Comment (janos) [inline bzzeth/bzzeth_test.go]: This check is probably not correct. If p1 is not nil, then break and cause the error on line 229 `if p1 != nil {`. https://travis-ci.org/ethersphere/swarm/jobs/584633395#L1013 The correct check should be here `p1 == nil` as we are waiting for peer not to be connected.

I missed this mistake in the previous review, as I did it in the rush.

**Review by janos — CHANGES_REQUESTED** [review]
There is a logical error in TestBzzBzzHandshakeWithMessage condition check causing the test to fail.

File: bzzeth/bzzeth_test.go (hunk 9 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go]: oopsss.... Thanks for catching this...
Fixed now  and changed to functions as you requested.

File: bzzeth/bzzeth_test.go (hunk 7 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go:174]: Done

File: bzzeth/bzzeth_test.go (hunk 8 above)
Comment (jmozah) [reply bzzeth/bzzeth_test.go:214]: Done

**Review by janos — APPROVED** [review]
Thanks Zahoor! LGTM.

**Review by zelig — APPROVED** [review]
approved but https://github.com/ethersphere/swarm/issues/1756
