### PR TITLE
cmd/swarm-smoke: add flag to bail on error

### LINKED ISSUE #1622: update smoke tests with a flag to exit on `chunk not found at max prox host`
Currently we have two ways of syncing chunks in Swarm - pull-sync (in `master`), and push-sync (in progress).

We are getting more confident with the syncing functionality of Swarm, so when we run a deployment that is stable (one where Swarm nodes are not supposed to exit or be killed), we should have the option to fail the smoke tests if a chunk is not found at their expected nodes.

Therefore I suggest we add a flag `--fail-on-sync-error` (or similar), which will exit the smoke test if a chunk is not found at all its max prox hosts (for pull syncing) or at the most closest node (for push syncing).

Obviously this smoke test makes sense only when we run it on a deployment that is on on-demand instances.

cc @acud @skylenet

### PR DESCRIPTION
**Pull request by acud**
This PR adds a `--bail` flag to the smoke test binary which tells the upload and sync test to bail on any intermediate errors found (such as `chunk not found max prox` and `chunk at less than two hosts`)

fixes #1622

### CODE REVIEW

**Review by janos — APPROVED** [review]

**Review by nonsense — APPROVED** [review]

File: cmd/swarm-smoke/upload_and_sync.go [hunk 1]
```diff
@@ -179,7 +183,7 @@ func trackChunks(testData []byte) error {
 // addrs - a slice with all uploaded chunk refs
 // allHostChunks - host->bit vector, showing what chunks are present on what hosts
 // bzzAddrs - host->bzz address, used when determining the most proximate host for a given chunk
-func checkChunksVsMostProxHosts(addrs []storage.Address, allHostChunks map[string]string, bzzAddrs map[string]string) {
+func checkChunksVsMostProxHosts(addrs []storage.Address, allHostChunks map[string]string, bzzAddrs map[string]string) error {
```
Comment (nonsense) [inline cmd/swarm-smoke/upload_and_sync.go:186]: @acud looks like this is no longer run for `pushsync` - it appears to be only called behind the flag `syncDelay`, and not behind `pushsyncDelay`.

Comment (acud) [reply cmd/swarm-smoke/upload_and_sync.go:186]: i fixed this @nonsense, please have a look at https://github.com/ethersphere/swarm/pull/1793/files#diff-4545af8f111f99eb44a69ef9b620c46fR311

**Review by nonsense — APPROVED** [review]
