### PR TITLE
 swarm/network/stream/delivery: byte comparison on error nil

### LINKED ISSUE #576: panic in processReceivedChunks
an unexpected panic while running `swarm-network-rewrite`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xbba2e9]

goroutine 45 [running]:
github.com/ethereum/go-ethereum/swarm/network/stream.(*Delivery).processReceivedChunks(0xc420a0b4a0)
	/home/e/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:212 +0x119
created by github.com/ethereum/go-ethereum/swarm/network/stream.NewDelivery
	/home/e/go/src/github.com/ethereum/go-ethereum/swarm/network/stream/delivery.go:60 +0xbe
```

### PR DESCRIPTION
**Pull request by acud**
hopefully resolves #576

### CODE REVIEW

**Review by holisticode — APPROVED** [review]

**Review by gbalint — APPROVED** [review]

File: swarm/network/stream/delivery.go [hunk 1]
```diff
@@ -209,10 +209,10 @@ R:
 
 		// this should be has locally
 		chunk, err := d.db.Get(req.Key)
-		if !bytes.Equal(chunk.Key, req.Key) {
-			panic(fmt.Errorf("processReceivedChunks: chunk key %s != req key %s (peer %s)", chunk.Key.Hex(), req.Key.Hex(), req.peer.ID()))
-		}
 		if err == nil {
+			if !bytes.Equal(chunk.Key, req.Key) {
+				panic(fmt.Errorf("processReceivedChunks: chunk key %s != req key %s (peer %s)", chunk.Key.Hex(), req.Key.Hex(), req.peer.ID()))
+			}
```
Comment (gbalint) [inline swarm/network/stream/delivery.go]: Minor thing, not a blocker: go convention is to first check the error case. I would just start with the
`if err != nil`, then basically everything in the loop can be in that if branch, and then if err is nil then check for the bytes.Equal, and we don't even need the `continue R` then.

Comment (zelig) [reply swarm/network/stream/delivery.go]: :+1: this check is not needed in fact, remnants of THE BUG hunt.

Comment (justelad) [reply swarm/network/stream/delivery.go]: @zelig so can i remove the check?
