### PR TITLE
Integrate encryption into dpa and chunker

### LINKED ISSUE #270: Fix concurrent map writes on chunker_test.go
```
ok      github.com/ethereum/go-ethereum/swarm/services/swap/swap    0.044s    coverage: 65.3% of statements
fatal error: concurrent map writes
goroutine 84612 [running]:
runtime.throw(0x62622e, 0x15)
    C:/go/src/runtime/panic.go:605 +0x7c fp=0x1275aef0 sp=0x1275aee4 pc=0x42a65c
runtime.mapassign_faststr(0x5ec980, 0x12377620, 0x1340eb40, 0x40, 0x40)
    C:/go/src/runtime/hashmap_fast.go:685 +0x472 fp=0x1275af48 sp=0x1275aef0 pc=0x40c6a2
github.com/ethereum/go-ethereum/swarm/storage.(*chunkerTester).Split.func1(0x12867840, 0x1340ea80, 0x12867800, 0x1283ddd0, 0x8, 0x5f3720)
    C:/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/chunker_test.go:68 +0x142 fp=0x1275afd8 sp=0x1275af48 pc=0x5b7d02
runtime.goexit()
    C:/go/src/runtime/asm_386.s:1635 +0x1 fp=0x1275afdc sp=0x1275afd8 pc=0x4526c1
created by github.com/ethereum/go-ethereum/swarm/storage.(*chunkerTester).Split
    C:/gopath/src/github.com/ethereum/go-ethereum/swarm/storage/chunker_test.go:59 +0x2
```

### PR DESCRIPTION
**Pull request by gbalint**
This PR is the integration of the encrpytion package into DPA and Chunker.

The goal was to encapsulate the encryption/decryption into a Putter and Getter interface, which stores and retrieves chunks.
Putter and Getter works with byte slices and not Chunk objects. So it handles the hashing and the Chunk creation. So all this can be removed from chunker, which can just directly use Putter.Put and Getter.Get with byte slices to store and retrieve chunks.
There is a HasherStore implementation of Putter and Getter which decides on whether to decrypt or not base on key length. One HasherStore instance is used for just one chunk storage/retrieval, so it can be initialized whether to encrypt or not when putting.
Another change is that the chunker objects are not reused anymore for multiple parallel split/join/append requests. This made the code much simpler, because the object itself can store the data necessary for the chunking task, no need to pass down a lot of parameters to the function calls.

fixes  #270 #280 #281 #289

### CODE REVIEW

File: swarm/storage/chunker.go [hunk 1]
```diff
@@ -245,107 +245,79 @@ func (self *TreeChunker) split(depth int, treeSize int64, key Key, data io.Reade
...
 }
 
 // implements the Joiner interface
-func (self *TreeChunker) Join(key Key, chunkC chan *Chunk, depth int) LazySectionReader {
+func (self *TreeChunker) Join(key Key, getter Getter, depth int) LazySectionReader {
 	return &LazyChunkReader{
-		key:       key,
-		chunkC:    chunkC,
+		key: key,
+		// chunkC:    chunkC,
```
Comment (zelig) [inline swarm/storage/chunker.go]: remove commented line

File: swarm/storage/chunker.go [hunk 2]
```diff
@@ -245,107 +245,79 @@ func (self *TreeChunker) split(depth int, treeSize int64, key Key, data io.Reade
...
 		chunkSize: self.chunkSize,
 		branches:  self.branches,
 		hashSize:  self.hashSize,
 		depth:     depth,
```
Comment (zelig) [inline swarm/storage/chunker.go]: comment on depth should be added (TODO)?

File: swarm/storage/hasherstore.go [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+}
+
+func newChunkEncryption() *chunkEncryption {
+	return &chunkEncryption{
+		spanEncryption: encryption.New(0, math.MaxUint32, sha3.NewKeccak256),
+		dataEncryption: encryption.New(4096, 0, sha3.NewKeccak256),
+	}
+}
+
+func NewHasherStore(chunkStore ChunkStore, hashFunc SwarmHasher, toEncrypt bool) *hasherStore {
```
Comment (zelig) [inline swarm/storage/hasherstore.go]: comment exported functions

File: swarm/storage/hasherstore.go [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+		}
+	}
+	chunk := h.createChunk(c, size)
+
+	// need to do this parallelly
+	h.store.Put(chunk)
+
+	return Reference(append(chunk.Key, encryptionKey...)), nil
+
+	//TODO: implement wait for storage
```
Comment (zelig) [inline swarm/storage/hasherstore.go]: remove

File: swarm/storage/pyramid.go [hunk 5]
```diff
@@ -494,8 +483,8 @@ func (self *PyramidChunker) prepareChunks(isAppend bool, chunkLevel [][]*TreeEnt
 		workers := self.getWorkerCount()
 		if int64(len(jobC)) > workers && workers < ChunkProcessors {
 			self.incrementWorkerCount()
-			storageWG.Add(1)
-			go self.processor(self.workerCount, jobC, chunkC, errC, quitC, storageWG)
+			// storageWG.Add(1)
```
Comment (zelig) [inline swarm/storage/pyramid.go]: remove

**Review by zelig — CHANGES_REQUESTED** [review]

File: swarm/storage/dpa.go [hunk 6]
```diff
@@ -95,83 +84,85 @@ func NewDPA(store ChunkStore, params *ChunkerParams) *DPA {
...
-func (self *DPA) Stop() {
-	self.lock.Lock()
-	defer self.lock.Unlock()
-	if !self.running {
-		return
-	}
-	self.running = false
-	close(self.quitC)
-}
+// func (self *DPA) Start() {
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/dpa.go]: Fixed in db1b51aa15aeb5fe2cae8d1bb21fb641adb7faf9

File: swarm/storage/pyramid.go [hunk 7]
```diff
@@ -195,6 +189,9 @@ func (self *PyramidChunker) Split(data io.Reader, size int64, chunkC chan *Chunk
 	}()
 
 	defer close(quitC)
+	defer func() {
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/pyramid.go]: Fixed in f32d4ccca55c57de559174ba876b5bcc419a087e

File: swarm/storage/pyramid.go [hunk 8]
```diff
@@ -203,28 +200,25 @@ func (self *PyramidChunker) Split(data io.Reader, size int64, chunkC chan *Chunk
 		}
 	case <-time.NewTimer(splitTimeout).C:
 	}
-	return rootKey, storageWG.Wait, nil
+	return rootKey, func() { return }, nil
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/pyramid.go]: This was before wait was implemented hasherstore. Proper wait implementation is added in f32d4ccca55c57de559174ba876b5bcc419a087e

File: swarm/storage/chunker.go (hunk 1 above)
Comment (gbalint) [reply swarm/storage/chunker.go]: Fixed in f32d4ccca55c57de559174ba876b5bcc419a087e

File: swarm/storage/hasherstore.go (hunk 3 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: Fixed in 8016f18cf13758bab198eff526a1b3726ab256d6

File: swarm/storage/hasherstore.go (hunk 4 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: I removed this and added proper wait implementation in f32d4ccca55c57de559174ba876b5bcc419a087e

File: swarm/storage/pyramid.go (hunk 5 above)
Comment (gbalint) [reply swarm/storage/pyramid.go]: Fixed in f32d4ccca55c57de559174ba876b5bcc419a087e

File: swarm/storage/chunker_test.go [hunk 9]
```diff
@@ -263,7 +174,7 @@ func TestSha3ForCorrectness(t *testing.T) {
 
 }
 
-func TestDataAppend(t *testing.T) {
```
Comment (nonsense) [inline swarm/storage/chunker_test.go]: @gbalint why is this commented out?

File: swarm/storage/hasherstore.go [hunk 10]
```diff
@@ -0,0 +1,223 @@
+// Copyright 2016 The go-ethereum Authors
```
Comment (nonsense) [inline swarm/storage/hasherstore.go]: Bump up copyright to 2018.

File: swarm/storage/hasherstore.go [hunk 11]
```diff
@@ -0,0 +1,223 @@
...
+		}
+	}
+	chunk := h.createChunk(c, size)
+
+	h.storeChunk(chunk)
+
+	return Reference(append(chunk.Key, encryptionKey...)), nil
+}
+
+// Returns data of the chunk with the given reference (retrieved from the ChunkStore of hasherStore).
```
Comment (nonsense) [inline swarm/storage/hasherstore.go]: Nitpick, but godoc comments should start with the name of the of the symbol described. Applies to multiple places. https://blog.golang.org/godoc-documenting-go-code

File: swarm/storage/hasherstore.go [hunk 12]
```diff
@@ -0,0 +1,223 @@
...
+		var err error
+		chunkData, err = h.decryptChunkData(chunkData, encryptionKey)
+		if err != nil {
+			return nil, err
+		}
+	}
+	return chunkData, nil
+}
+
+// The Close() indicates that no more chunks will be put with the hasherStore, so the Wait
```
Comment (nonsense) [inline swarm/storage/hasherstore.go]: Close indicates...

File: swarm/storage/hasherstore.go [hunk 13]
```diff
@@ -0,0 +1,223 @@
...
+	return &chunkEncryption{
+		spanEncryption: encryption.New(0, math.MaxUint32, sha3.NewKeccak256),
+		dataEncryption: encryption.New(4096, 0, sha3.NewKeccak256),
+	}
+}
+
+// NewHasherStore creates a hasherStore object, which implements Putter and Getter interfaces.
+// With the HasherStore you can put and get chunk data (which is just []byte) into a ChunkStore
+// and the hasherStore will take core of encryption/decryption of data if necessary
+func NewHasherStore(chunkStore ChunkStore, hashFunc SwarmHasher, toEncrypt bool) *hasherStore {
```
Comment (nonsense) [inline swarm/storage/hasherstore.go:52]: I think `HasherStore` is a good candidate for a few unit tests. It is a new type, and having a bunch of simple unit tests would help documenting it and reduce the cognitive load on readers, since a few simple examples of actual use of the type speak much more than any comments.

File: swarm/storage/hasherstore.go [hunk 14]
```diff
@@ -0,0 +1,223 @@
...
+	hashFunc        SwarmHasher
+	chunkEncryption *chunkEncryption
+	refSize         int64
+	wg              *sync.WaitGroup
+	closed          chan struct{}
+}
+
+func newChunkEncryption() *chunkEncryption {
+	return &chunkEncryption{
+		spanEncryption: encryption.New(0, math.MaxUint32, sha3.NewKeccak256),
```
Comment (gbalint) [inline swarm/storage/hasherstore.go]: Instead of MaxUint32 let's use the branches value

File: swarm/storage/hasherstore.go [hunk 15]
```diff
@@ -0,0 +1,223 @@
...
+	return c, nil
+}
+
+func (h *hasherStore) RefSize() int64 {
+	return h.refSize
+}
+
+func (h *hasherStore) storeChunk(chunk *Chunk) {
+	// need to do this parallelly
+	if h.store != nil {
```
Comment (nonsense) [inline swarm/storage/hasherstore.go]: Why are we checking for `h.store`? Shouldn't we just assume it is there?

File: swarm/storage/hasherstore.go [hunk 16]
```diff
@@ -0,0 +1,223 @@
...
+	h.storeChunk(chunk)
+
+	return Reference(append(chunk.Key, encryptionKey...)), nil
+}
+
+// Returns data of the chunk with the given reference (retrieved from the ChunkStore of hasherStore).
+// If the data is encrypted and the reference contains an encryption key, it will be decrypted before
+// return.
+func (h *hasherStore) Get(ref Reference) (ChunkData, error) {
+	if h.store == nil {
```
Comment (nonsense) [inline swarm/storage/hasherstore.go]: Why are we checking for `h.store == nil`? Does this type make sense if h.store is nil?

File: swarm/storage/pyramid.go [hunk 17]
```diff
@@ -75,15 +75,61 @@ const (
...
-	return &ChunkerParams{
-		Branches: DefaultBranches,
-		Hash:     SHA3Hash,
+func NewPyramidSplitterParams(key Key, reader io.Reader, putter Putter, getter Getter, branches int64) *PyramidSplitterParams {
+	hashSize := putter.RefSize()
+	return &PyramidSplitterParams{
+		SplitterParams: SplitterParams{
+			ChunkerParams: ChunkerParams{
+				// TODO: use chunkSize as parameter, because that is the constant
+				branches: 4096 / hashSize,
```
Comment (nonsense) [inline swarm/storage/pyramid.go]: Maybe extract 4096 as a constant and document it, since it is used at at least 3 places.

File: swarm/storage/types.go [hunk 18]
```diff
@@ -264,14 +265,32 @@ type Splitter interface {
 	   The caller gets returned an error channel, if an error is encountered during splitting, it is fed to errC error channel.
 	   A closed error signals process completion at which point the key can be considered final if there were no errors.
 	*/
-	Split(io.Reader, int64, chan *Chunk) (Key, func(), error)
+	Split() (Key, func(), error)
```
Comment (nonsense) [inline swarm/storage/types.go]: Comments of this interface no longer make sense, as they refer to arguments that no longer exist.

**Comment by nonsense** [comment]
Overall LGTM, but there are a few things that need to be fixed and cleared up.

**Review by nonsense — CHANGES_REQUESTED** [review]
.

File: swarm/storage/hasherstore.go [hunk 19]
```diff
@@ -0,0 +1,223 @@
...
+		go func() {
+			<-chunk.dbStored
+			h.wg.Done()
+		}()
+		h.store.Put(chunk)
+	}
+}
+
+func parseReference(ref Reference) (Key, encryption.Key, error) {
+	encryptedKeyLength := KeyLength + encryption.KeyLength
```
Comment (gbalint) [inline swarm/storage/hasherstore.go]: Do not use KeyLength, but hashSize

File: swarm/storage/hasherstore.go (hunk 16 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: There is one place where we use it with nil, because we only need it for hashing: https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite-encryption/cmd/swarm/hash.go#L41
This cmd line tool just gets the hash without storing data. So I think it makes sense to have a nil store if you only need the "hasher" functionality, but not the "store".

File: swarm/storage/pyramid.go (hunk 17 above)
Comment (gbalint) [reply swarm/storage/pyramid.go]: I agree, that is why I have the TODO in the line before, I'm fixing this.

File: swarm/storage/hasherstore.go (hunk 16 above)
Comment (nonsense) [reply swarm/storage/hasherstore.go]: I think we should just implement a mock/dummy memory store and use that, when we don't care about the storing functionality, rather than add the load of having to check for nil everywhere we use the h.store.

Comment (nonsense) [reply swarm/storage/hasherstore.go]: Another point is that we keep on passing multiple nil and boolean arguments to methods, which gets very confusing (I think @holisticode has a similar comment in another PR at the moment).

I think we should be encapsulate behaviour with interfaces, rather than in this way.

File: swarm/storage/types.go (hunk 18 above)
Comment (gbalint) [reply swarm/storage/types.go]: I realized that we don't even need these interfaces anymore, they are not used anywhere: 424b11dc1b5dd1d0efc46cb9d8a2fe36ebb8e7ef

File: swarm/storage/hasherstore.go (hunk 15 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: There is one place where we use it with nil, because we only need it for hashing: https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite-encryption/cmd/swarm/hash.go#L41
This cmd line tool just gets the hash without storing data. So I think it makes sense to have a nil store if you only need the "hasher" functionality, but not the "store".

File: swarm/storage/hasherstore.go (hunk 13 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go:52]: I totally agree, I'm adding a few

File: swarm/storage/hasherstore.go (hunk 12 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: Fixed in 2329cfb50e285f49e3c4f59eb6f6e5ce09acac27

File: swarm/storage/pyramid.go [hunk 20]
```diff
@@ -75,15 +75,61 @@ const (
...
+			},
+			reader: reader,
+			putter: putter,
+			key:    key,
+		},
+		getter: getter,
+	}
+}
+
+func NewTreeSplitterParams(reader io.Reader, putter Putter, size int64, branches int64) *TreeSplitterParams {
```
Comment (nolash) [inline swarm/storage/pyramid.go]: Why is this in `pyramid.go` when `TreeSplitter` type declaration is in `chunker.go`?

File: swarm/storage/pyramid.go [hunk 21]
```diff
@@ -112,41 +158,56 @@ func NewTreeEntry(pyramid *PyramidChunker) *TreeEntry {
...
 type chunkJob struct {
-	key       Key
-	chunk     []byte
-	size      int64
-	parentWg  *sync.WaitGroup
-	chunkType int // used to identify the tree related chunks for debugging
-	chunkLvl  int // leaf-1 is level 0 and goes upwards until it reaches root
+	key      Key
+	chunk    []byte
+	parentWg *sync.WaitGroup
```
Comment (nolash) [inline swarm/storage/pyramid.go:137]: I don't understand why this is in `pyramid.go`. A `chunkJob` is chunker agnostic, isn't it?

File: swarm/storage/pyramid.go [hunk 22]
```diff
@@ -168,227 +229,203 @@ func (self *PyramidChunker) decrementWorkerCount() {
...
+	ref, err := self.putter.Put(job.chunk)
+	if err != nil {
+		self.errC <- err
+	}
 
 	// report hash of this chunk one level up (keys corresponds to the proper subslice of the parent chunk)
-	copy(job.key, h)
+	copy(job.key, ref)
 
 	// send off new chunk to storage
```
Comment (nolash) [inline swarm/storage/pyramid.go:297]: obsolete comment

File: swarm/storage/pyramid.go [hunk 23]
```diff
@@ -168,227 +229,203 @@ func (self *PyramidChunker) decrementWorkerCount() {
...
 	chunkWG := &sync.WaitGroup{}
 
 	self.incrementWorkerCount()
 
-	go self.processor(self.workerCount, jobC, chunkC, errC, quitC, storageWG)
+	go self.processor(self.workerCount)
 
 	parent := NewTreeEntry(self)
-	var unfinishedChunk *Chunk
+	var unfinishedChunk ChunkData
```
Comment (nolash) [inline swarm/storage/pyramid.go]: Should this be `unfinishedChunkData` for clarity?

File: swarm/storage/types.go [hunk 24]
```diff
@@ -264,14 +265,32 @@ type Splitter interface {
...
+}
+
+type ChunkData []byte
+
+type Reference []byte
+
+type Putter interface {
+	Put(ChunkData) (Reference, error)
+	// Length of the Reference created by this Putter
+	RefSize() int64
```
Comment (nolash) [inline swarm/storage/types.go]: again, why 64?

**Review by nolash — COMMENTED** [review]
In `swarm/api` the calls to `DPA.Store` pass `false` for the `toEncrypt` parameter. Is it correct that this should be hardcoded?

**Comment by nolash** [comment]
5 of my comments got hidden I see. I don't know what that means...

File: swarm/storage/chunker_test.go [hunk 25]
```diff
@@ -263,7 +174,7 @@ func TestSha3ForCorrectness(t *testing.T) {
...
+func XTestDataAppend(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (nolash) [reply swarm/storage/chunker_test.go]: @nonsense `git grep -B1` would do the trick, probably ;) 

I won't argue convention, because I don't know. However, what I like about `t.Skip()` is that it rats on which tests are skipped and (hopefully) includes a reason why when someone (maybe other than developer) tries to run them.

[the remark this answers is not in the document]
Comment (nonsense) [reply swarm/storage/chunker_test.go]: You are right, I haven't noticed that with `XTest` tests do not appear with a `Skip` when running `go test -v`.

Adding a reason inside t.Skip() would definitely be nice, I had to comment on this ticket when I saw that this test is disabled.

In this case I would be happy to follow one convention or the other, depending how we agree as a team, just so that we are consistent ;)

File: swarm/storage/dpa_test.go [hunk 26]
```diff
@@ -39,17 +44,12 @@ func TestDPArandom(t *testing.T) {
...
-	chunker := NewTreeChunker(NewChunkerParams())
-	dpa := &DPA{
-		Chunker:    chunker,
-		ChunkStore: localStore,
-	}
-	dpa.Start()
-	defer dpa.Stop()
+
+	dpa := NewDPA(localStore, NewDPAParams())
 	defer os.RemoveAll("/tmp/bzz")
```
Comment (janos) [inline swarm/storage/dpa_test.go:49]: Shouldn't this be `defer os.RemoveAll(tdb.dir)`? I know that this is the old code, but this test may be improved here as well.

**Review by janos — COMMENTED** [review]
Just a suggestion for dpa Start and Stop functions. If the intension is to reintroduce workers for the dpa, would it be easer to make this methods noop and not remove them from where they are called. Or maybe to even remove the Start func and start the processing loop in the constructor, and keep only the Stop.

File: swarm/storage/chunker_test.go (hunk 9 above)
Comment (gbalint) [reply swarm/storage/chunker_test.go]: @nonsense accident, I reenabled it in d8ee6a163b535dfaec483f1d04d9134056b5eee1

File: swarm/storage/chunker.go [hunk 27]
```diff
@@ -510,13 +506,13 @@ func (s *LazyChunkReader) Seek(offset int64, whence int) (int64, error) {
...
 	case 2:
-		if s.chunk == nil { //seek from the end requires rootchunk for size. call Size first
+		if s.chunkData == nil { //seek from the end requires rootchunk for size. call Size first
 			_, err := s.Size(nil)
 			if err != nil {
 				return 0, fmt.Errorf("can't get size: %v", err)
 			}
 		}
-		offset += s.chunk.Size
+		offset += s.chunkData.Size()
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker.go:563]: @nolash I think you have to specify a negative offset in case of SeekEnd whence, so no. For sure I did not change how this works, just modified the chunk to chunkData.

File: swarm/storage/hasherstore.go (hunk 10 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: @nonsense Fixed in 46e98327d70708b29706cbc7f87e975306b0c2a1

File: swarm/storage/hasherstore.go (hunk 11 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: @nonsense Sure, it is not a nitpick, I'm happy to receive these kind of review comments. It is fixed in 46e98327d70708b29706cbc7f87e975306b0c2a1

File: swarm/storage/hasherstore.go (hunk 16 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: @nonsense Ok, I agree, I implemented this: c03ae51e67eb88ab7f43c3594a0263b0d8e73915
Is this what you meant?

Comment (nonsense) [reply swarm/storage/hasherstore.go]: Yes, that's one way of doing it, and it is already much better than before. I would have just used the `MemStore`, so that we don't have yet another impl. - we would just push the chunks to a memory store for the duration of the test, which is fine, even if we don't need them.

This `Get` is not technically correct as it neither returns a chunk, nor an error, which might be buggy in some places.
```
+// Gut doesn't store anything it is just here to implement ChunkStore
+func (d *FakeChunkStore) Get(Key) (*Chunk, error) {
+	return nil, nil
+}
```

File: swarm/storage/pyramid.go (hunk 17 above)
Comment (gbalint) [reply swarm/storage/pyramid.go]: @nonsense Fixed in 68cf01eb4fe28e729a1b32eafe1959c28a1b36a4

File: swarm/storage/chunker_test.go [hunk 28]
```diff
@@ -40,136 +39,46 @@ type test interface {
...
-			}
-		}()
-	}
-	var w func()
-	key, w, err = chunker.Append(rootKey, data, chunkC)
-	if err != nil && expectedError == nil {
-		err = fmt.Errorf("Append error: %v", err)
-	}
+func (t *testChunkStore) Close() {
+	return
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker_test.go]: @janos Fixed in 49a4d9cf1c3428e7bebeccccb0d262fb1e860d25

**Comment by gbalint** [comment]
@nolash false is hardcoded as toEncrypt only temporarily, because this PR does not yet contain any code to wire the new encryption feature of DPA to api.go or server.go. That will happen in a different API

**Comment by gbalint** [comment]
@janos There is no need to reintroduce workers into DPA, as DPA does not do storage anymore. There are workers in chunker which call hasherStore Put/Get parallelly, and the store itself is asynchronous. So even in hasherStore there is no need for workers in my opinion.

**Comment by gbalint** [comment]
@nolash A comment is hidden if the code which you commented on has been changed. But I'm checking the hidden comments too...

File: swarm/storage/pyramid.go (hunk 21 above)
Comment (gbalint) [reply swarm/storage/pyramid.go:137]: @nolash No, only the pyramid chunker uses the chunkJob type, it is an implementation specific private thing.

File: swarm/storage/pyramid.go (hunk 23 above)
Comment (gbalint) [reply swarm/storage/pyramid.go]: @nolash Fixed in 3358a59371fa05a4be83ff080df131b5534096b4

Comment (gbalint) [reply swarm/storage/pyramid.go]: @nolash Fixed in 484e22c94864832b528b8506292f977603276a6a

File: swarm/storage/chunker.go [hunk 29]
```diff
@@ -235,119 +292,89 @@ func (self *TreeChunker) split(depth int, treeSize int64, key Key, data io.Reade
...
-				// now we got the hashes in the chunk, then hash the chunks
-				self.hashChunk(hasher, job, chunkC, storeWg)
-			case <-quitC:
+
+				h, err := self.putter.Put(job.chunk)
+				if err != nil {
+					self.errC <- err
+					return
+				}
+				copy(job.key, h)
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker.go:370]: @nolash Putter.Put doesn't depend on the hashJob type used by the chunker. However, probably this type is not necessary. Let me add that both chunker and pyramid could be refactored more heavily, but my primary goal was not that but to integrate encryption.

File: swarm/storage/chunker.go [hunk 30]
```diff
@@ -125,56 +187,51 @@ func (self *TreeChunker) decrementWorkerCount() {
...
 
-	jobC := make(chan *hashJob, 2*ChunkProcessors)
-	wg := &sync.WaitGroup{}
-	storeWg := &sync.WaitGroup{}
-	errC := make(chan error)
-	quitC := make(chan bool)
-
 	self.incrementWorkerCount()
-	self.runHashWorker(jobC, chunkC, errC, quitC, storeWg)
+	self.runWorker()
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker.go]: @nolash Good catch, fixed in b0ab49ffd77a0808267385cb76fabcc929cf111a

File: swarm/storage/chunker.go (hunk 2 above)
Comment (gbalint) [reply swarm/storage/chunker.go]: Fixed in 582c6e53a54f08ecdbe771c195483e640803b50b

File: swarm/storage/hasherstore.go (hunk 13 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go:52]: Unit test added in cdc7bed7ab5e9e3fa31b0f4b3a473d15f70c7b64

File: swarm/storage/hasherstore.go [hunk 31]
```diff
@@ -0,0 +1,223 @@
...
+type chunkEncryption struct {
+	spanEncryption encryption.Encryption
+	dataEncryption encryption.Encryption
+}
+
+type hasherStore struct {
+	store           ChunkStore
+	hashFunc        SwarmHasher
+	chunkEncryption *chunkEncryption
+	refSize         int64
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/hasherstore.go]: I just inherited from the earlier hashSize here: https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/swarm/storage/pyramid.go#L126
But I agree, however, is it ok to fix that a later PR?

File: swarm/storage/hasherstore.go (hunk 14 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go]: Fixed in b737d496ea0e48fdc5bf40e3ad71850ae2f544dd

File: swarm/storage/chunker_test.go [hunk 32]
```diff
@@ -379,63 +275,54 @@ func benchReadAll(reader LazySectionReader) {
...
+		key, wait, err := PyramidSplit(data, putGetter, putGetter)
 		if err != nil {
-			tester.t.Fatalf(err.Error())
+			t.Fatalf(err.Error())
 		}
 		wait()
-		chunkC = make(chan *Chunk, 1000)
-		quitC := make(chan bool)
-		reader := tester.Join(chunker, key, i, chunkC, quitC)
+		reader := TreeJoin(key, putGetter, 0)
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker_test.go:273]: @nolash Your comment is valid, but since this is really not the scope of my PR to refactor the benchmark tests, I just renamed the function names, see c59a6a477bc8cd21fbbd79c96f60396cb30258dc
Is it better this way?

File: swarm/storage/chunker_test.go [hunk 33]
```diff
@@ -444,40 +331,37 @@ func benchmarkSplitPyramidSHA3(n int, t *testing.B) {
...
 	for i := 0; i < t.N; i++ {
-		cp := NewChunkerParams()
-		cp.Hash = BMTHash
-		splitter := NewPyramidChunker(cp)
-		tester := &chunkerTester{t: t}
 		data := testDataReader(n)
-		_, _, err := tester.Split(splitter, data, int64(n), nil, nil)
+		putGetter := newTestHasherStore(nil, BMTHash)
+
+		_, _, err := TreeSplit(data, int64(n), putGetter)
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker_test.go]: @nolash Nice catch, fixed in bc32751e88cb78a4b3454d8539070b3f2ee32ec6

File: swarm/storage/chunker_test.go [hunk 34]
```diff
@@ -444,40 +331,37 @@ func benchmarkSplitPyramidSHA3(n int, t *testing.B) {
...
 		if err != nil {
-			tester.t.Fatalf(err.Error())
+			t.Fatalf(err.Error())
 		}
 		wait()
-		chunkC = make(chan *Chunk, 1000)
 
-		_, wait, err = tester.Append(chunker, key, data1, chunkC, nil)
+		putGetter = newTestHasherStore(chunkStore, SHA3Hash)
+		_, wait, err = PyramidAppend(key, data1, putGetter, putGetter)
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/chunker_test.go:347]: @nolash Your comment is valid, but since this is really not the scope of my PR to refactor the benchmark tests, I just renamed the function names, see c59a6a477bc8cd21fbbd79c96f60396cb30258dc
Is it better this way?

File: swarm/storage/chunker_test.go [hunk 35]
```diff
@@ -40,136 +39,45 @@ type test interface {
...
-				chunk.Size = int64(binary.LittleEndian.Uint64(chunk.SData[0:8]))
-				close(chunk.C)
-				i++
-			}
-		}
-	}()
-
-	reader := chunker.Join(key, chunkC, 0)
-	return reader
+func newTestHasherStore(chunkStore ChunkStore, hash string) *hasherStore {
```
Comment (nonsense) [inline swarm/storage/chunker_test.go]: Nitpick, but I think this method is redundant - just use directly the `NewHasherStore`.

**Review by nonsense — APPROVED** [review]
provided tests are passing - LGTM. there are many small things we can amend or refactor in the future, but I think this PR is already an improvement.

File: swarm/storage/hasherstore.go (hunk 13 above)
Comment (gbalint) [reply swarm/storage/hasherstore.go:52]: @nonsense  Nice, I committed it in ba258d747e676201bde3ace976bef0432bbb8d6e

**Review by janos — APPROVED** [review]
Minor comments, but the PR is 👍

File: swarm/storage/types.go [hunk 36]
```diff
@@ -206,7 +207,7 @@ func (c *Chunk) WaitToStore() {
 func FakeChunk(size int64, count int, chunks []*Chunk) int {
 	var i int
 	hasher := MakeHashFunc(SHA3Hash)()
-	chunksize := getDefaultChunkSize()
+	chunksize := DefaultChunkSize
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/types.go]: @janos Fixed in 0bfe320a30a76721a31577e5ef597d42c178c039

File: swarm/storage/hasherstore.go [hunk 37]
```diff
@@ -0,0 +1,227 @@
...
+	h.wg.Add(1)
+	go func() {
+		<-chunk.dbStored
+		h.wg.Done()
+	}()
+	h.store.Put(chunk)
+}
+
+func parseReference(ref Reference) (Key, encryption.Key, error) {
+	encryptedKeyLength := KeyLength + encryption.KeyLength
```
[the remark this answers is not in the document]
Comment (gbalint) [reply swarm/storage/hasherstore.go]: @janos I decided to make it a parameter as KeyLength is not constant, but the hashSize, which depends on the hash function, see 0bfe320a30a76721a31577e5ef597d42c178c039

[the remark this answers is not in the document]
Comment (janos) [reply swarm/storage/hasherstore.go]: 👍
