### PR TITLE
network: new stream! protocol and pull syncer implementation

### LINKED ISSUE #1105: Refactor updateSyncing function in swarm/network/stream
We have identified a problem that updateSyncing function in swarm/network/stream is very badly written and extremely hard to understand. We should change it as soon as possible as it may be a source of confusion, delayed PR approvals or even issues.

Related discussions:
https://github.com/ethereum/go-ethereum/pull/18355#discussion_r243701079
https://github.com/ethereum/go-ethereum/pull/18355#discussion_r247065159

### LINKED ISSUE #1203: Evaluate unit tests for stream package and add missing ones

### LINKED ISSUE #1204: Rewrite the stream package
Make it unit testable, not only with simulation.
Remove unneeded generalization.
Do not introduce unnecessary abstractions too early.
Revisit requirements.

### LINKED ISSUE #1234: network/stream: TestGetSubscriptionsRPC is flaky with -race (ratio: 22:1000)
**Problem**

```
--- FAIL: TestGetSubscriptionsRPC (0.37s)
    streamer_test.go:1332: Real subscriptions and expected amount don't match; real: 1, expected: 8
```

**Flaky ratio**
```
     20 FAIL
    980 PASS
```
~~*Note:* because of #1233  I did not get a 1000 runs as originally intended.~~

**How to reproduce**

`time go test -v -race -run TestGetSubscriptionsRPC -count 1000 github.com/ethereum/go-ethereum/swarm/network/stream`

*Note*: The test seems to be stable without `-race`.

### LINKED ISSUE #1246: network/stream: TestSyncingViaGlobalSync panic (invalid memory address)
In 3c48738c15a1f094f34cb95e355dda13db4c9415 we skip the test as it often panics on Travis with `-race`

**How to reproduce**
*TODO*

### LINKED ISSUE #1247: network/stream: investigate TestDeliveryFromNodes timeouts
From @zelig:
> this test really should not time out, it is either set to too small timeout duration or there's a bug.

src: https://github.com/ethersphere/go-ethereum/pull/1243#discussion_r258516601

**How to reproduce**

1) Create a branch.
2) Modify `.travis.yml` to run just the Race Detector job, but the whole suite. Timeout does not happen if the test runs just by itself. (Remove everything else from `- include` group.)
3) Push that branch to ethersphere and make sure your job gets triggered. [Travis builds](https://travis-ci.org/ethersphere/go-ethereum/builds)
=> The job should fail. (`TestDeliveryFromNodes github.com/ethereum/go-ethereum/swarm/network/stream`)

**Test run time**

*If run alone*

```
--- PASS: TestDeliveryFromNodes (77.97s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_2_200_skipCheck_true (4.40s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_2_200_skipCheck_false (4.51s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_4_200_skipCheck_true (5.92s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_4_200_skipCheck_false (5.76s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_8_200_skipCheck_true (8.99s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_8_200_skipCheck_false (9.27s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_16_200_skipCheck_true (19.27s)
    --- PASS: TestDeliveryFromNodes/testDeliveryFromNodes_16_200_skipCheck_false (19.87s)
```

**Questions**

* Do we care about the added complexity of `if testutil.RaceEnabled`?
* Do we expect to learn anything new if we run not just 2 and 4 nodes, but 8 and 16? 
* Does that - having more nodes - worth the extra 60s added to total testing time? **Even if we can run the tests, should we?**
~* Is this investigation and possible fix the best way to use our time?~ *obsolete*: tests are passing after https://github.com/ethereum/go-ethereum/pull/19443

### LINKED ISSUE #1393: improve tracing of syncing protocol
From a retrieve request perspective, the `simple-fetchers` PR should make it relatively easy to track a specific retrieve request and for a developer to understand what went wrong with it.

However in terms of syncing, at the moment it is very difficult to understand if it is working correctly, or when we find that a `chunk not found at max prox host` in smoke tests, debug what went wrong.

---

I think one of the reasons for this is that syncing is an ongoing process, whereas retrieve requests have a specific entrypoint and are therefore easy to trace.

---

One thing that we could do it attach a trace to every `SwarmSyncerServer` for every peer and po. Then in a network of 100 nodes, where every node has 20 peers, that would result in `100 * 20 * 16` traces for syncing. We could attach a root span to the `SwarmSyncerServer` and call `finish` on it every 30sec, during which we append useful information (number of batches, chunks synced, cursors, etc.).

### LINKED ISSUE #1451: rewrite pull syncer
pull syncer has a few edge case bugs that are very hard to trace and debug.

we sometimes do not get chunks at the expected nodes and it is very difficult to support these debugging efforts with the current syncer infrastructure.

work outline:
- [x] submit an initial [spec](https://github.com/ethersphere/swarm/pull/1454) to iterate on top of
- [x] write the protocol boilerplate for initialising a new protocol over the devp2p network

sync:
- [x] retrieve stream cursors upon node connection
- [x] drop cursors on node moved out of depth 
- [x] establish streams inside NN according to kademlia depth
- [x] make sure that stream cancellations happen on depth change
- [x] debounce mechanism

sync-localstore-intervals:
- [x] make sure closed intervals are always delivered from localstore pull

get stream < cursor (history priority):
- [x] test case for continuous intervals (no gaps)
- [x] test case for missing intervals (enclosing interval should still persist)

get stream > cursor (live priority):
- [x] test case for continuous intervals (no gaps)
- [x] ~test case for missing intervals (enclosing interval should still persist)~ difficult to test since intervals are fetched faster than they can be erased to create gaps. on hold

consistency:
- [x] test case for no duplicate chunks delivered
- [x] check no overlap between historical and live streaming
- [ ] make sync bins within depth feature toggle configurable and write test cases that validate syncing with it on and off

cluster/snapshot:
- [x] test that chunks are sent correctly in a star topology (adapt second test from `syncer_test.go` from existing `stream` package)
- [x] test that 3 nodes with full connectivity sync between them and that on each node will be the union of all three nodes' localstores
- [x] test that chunks are synced correctly in a larger full topology w/ discovery. this test vector needs more description

resilience:
- [ ] guaranty that there's always a live historical fetch with an unbounded stream
- [ ] check that existing historical and live historical stream fetchers terminate when depth changes and node moves out of depth

optimisations/benchmarking:
- [x] is it faster to concurrently deliver 3000 chunks in 3000 different messages between two nodes? or is it more effective to send one message with 3000 chunks? this should be easily measurable

tooling:
- [x] add assert for smoke tests to know when syncing is done

logging:
- ~how do add node identity to every logline our node outputs? related to https://github.com/ethersphere/swarm/issues/1393~

### LINKED ISSUE #1457: flake:  github.com/ethersphere/swarm/network/stream:TestStarNetworkSync
This test will be disabled temporarily until it's fixed/deleted.

To reproduce, enable the test again (if it's disabled) and run:

```
 go test -v github.com/ethersphere/swarm/network/stream -run 'TestStarNetworkSync' -count=5
```

Output:

```
=== RUN   TestStarNetworkSync
--- PASS: TestStarNetworkSync (30.31s)
=== RUN   TestStarNetworkSync
--- PASS: TestStarNetworkSync (30.32s)
=== RUN   TestStarNetworkSync
--- FAIL: TestStarNetworkSync (30.32s)
    syncer_test.go:451: checked chunks dont match numer of chunks. got 253 want 505
=== RUN   TestStarNetworkSync
--- PASS: TestStarNetworkSync (30.34s)
=== RUN   TestStarNetworkSync
--- FAIL: TestStarNetworkSync (30.29s)
    syncer_test.go:451: chunk not found
FAIL
FAIL    github.com/ethersphere/swarm/network/stream     151.712s
```

Example Trace:

```
WARN [06-11|13:07:13.361|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:13.361|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:13.922|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:13.922|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:14.512|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:14.512|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:15.116|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:15.116|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:15.693|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:15.693|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:16.286|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
WARN [06-11|13:07:16.286|github.com/ethersphere/swarm/network/kademlia.go:881] peerpot NNSet < NeighbourhoodSize 
ERROR[06-11|13:07:23.902|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="write tcp 127.0.0.1:33517->127.0.0.1:44240: write: broken pipe"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=4c144ac2f4ee4a86 err="shutting down"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=4c144ac2f4ee4a86 err="write tcp 127.0.0.1:35938->127.0.0.1:44904: use of closed network connection"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=4c144ac2f4ee4a86 err="shutting down"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=4c144ac2f4ee4a86 err="shutting down"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=a0109d6c41a317e8 err="shutting down"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=a0109d6c41a317e8 err="shutting down"
ERROR[06-11|13:07:28.179|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=594203c8fa170bec err="shutting down"
ERROR[06-11|13:07:28.180|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=594203c8fa170bec err="shutting down"
ERROR[06-11|13:07:28.180|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=0d529d1464743675 err="shutting down"
ERROR[06-11|13:07:28.185|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=0d529d1464743675 err="write tcp 127.0.0.1:35528->127.0.0.1:43353: use of closed network connection"
ERROR[06-11|13:07:28.185|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=6ff9a3f6f1f8019e err="write tcp 127.0.0.1:35212->127.0.0.1:38733: use of closed network connection"
ERROR[06-11|13:07:28.185|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=4ebda1ce79761129 err="write tcp 127.0.0.1:34823->127.0.0.1:41684: use of closed network connection"
ERROR[06-11|13:07:28.186|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=c55a176b1c185e52 err="write tcp 127.0.0.1:35908->127.0.0.1:45318: use of closed network connection"
ERROR[06-11|13:07:28.191|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=2653c3d78d1c11fd err="write tcp 127.0.0.1:52426->127.0.0.1:38730: use of closed network connection"
ERROR[06-11|13:07:39.357|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="write tcp 127.0.0.1:34140->127.0.0.1:45118: write: broken pipe"
ERROR[06-11|13:07:39.358|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="shutting down"
ERROR[06-11|13:07:50.506|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="shutting down"
ERROR[06-11|13:07:50.506|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="shutting down"
ERROR[06-11|13:07:50.506|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="write tcp 127.0.0.1:37300->127.0.0.1:34754: use of closed network connection"
ERROR[06-11|13:07:50.506|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="shutting down"
ERROR[06-11|13:07:50.507|github.com/ethersphere/swarm/network/stream/peer.go:94] Message send error, dropping peer        peer=427e0288b5a474d9 err="write tcp 127.0.0.1:33929->127.0.0.1:59614: write: connection reset by peer"
ERROR[06-11|13:07:50.859|github.com/ethersphere/swarm/network/stream/stream.go:397] error invalid hashes length (len: 40) 
--- FAIL: TestStarNetworkSync (30.63s)
    syncer_test.go:451: chunk not found
FAIL
coverage: 82.9% of statements
FAIL	github.com/ethersphere/swarm/network/stream	106.636s
````

### PR DESCRIPTION
**Pull request by acud**
This PR is the result of joint efforts in the core track to realise the exact, up to date requirements of the `stream!` protocol  and implement them so that their functionality and behavior is easier to reason about.

The design borrows _some_ code from the old `stream` package. Namely the way we manage bins we want to stream in the case of syncing and the existing intervals store. However everything else including tests have been built from the ground up.

The PR does not yet remove the existing `stream` code, does not move the `intervals` package, but rather builds on top of those. This is in order to decrease the strain of diffing those changes. These would be deferred to subsequent PRs after this one is merged.

The new stream implementation suggested in this PR brings more guarantees, better performance and safety to how we handle `streams`, namely:
- Spamming through `streams` is far less likely due to tight checking of wanted streams from a certain peer
- Spamming of unsolicited chunks is completely forbidden - a peer cannot send us the same chunk twice, a peer cannot send us a chunk that we did not request too (these are two different cases)
- Multiple chunks can now be delivered on the same `ChunkDelivery` message
- No duplicate chunks are sent between two peers

In terms of reduced complexity:
- Far less state is maintained on each side of the connection. Servers maintain `offers`, clients maintain `wants`

_PLEASE NOTE:_ that tests constitute about a half of this PR. Some of them overlap in functionality and will be removed, namely some of the tests in `cursors_test.go`.

Actionable items that still need to be addressed, however I would personally like to defer to a later PR:
- Move stream maintanance for the case of syncing out of the sync provider - the sync provider needs to only sink data to the stream protocol, not manage subscriptions. This, however, needs a bit more tweaking in terms of abstraction for stream - as it would require to expose certain subset of functionalities out of the `stream` package. In laymen terminology - we would need to call certain functions on `stream` when a depth change happens for example, but then also to have hooks on `stream` to know that a `StreamInfoRes` message has arrived and what to do accordingly....
- how to guaranty that historical and live streams are kept alive - we should have metrics to see at least on the smoke test environment that these streams keep on getting requested and served correctly
- verify that existing historical and live historical stream fetchers terminate when depth changes and node moves out of depth - this is not so trivial to test but the logic that does this is in the codebase
- `maxPeers` - old `stream` package had a notion of maximum peers we'd like to stream to/with. we have concluded partially that `kademlia` should somehow shield us from having to implement this at the moment, since number of connections are/should be enforced by `kademlia` at the moment. so this needs more info before we jump the gun to implement such a requirement
- proper tracing with jaeger and opentracing - need more info from @nonsense and @skylenet on how to do this properly
- Update diagrams

_**HOW TO REVIEW**_:
Since there is a fair amount of business logic here, a brief overview on how the protocol works is needed in order to facilitate an effective review process.
Flow is as follows:
- Stream protocol and Sync Provider are registered on `swarm.go`. Stream handles the protocol message exchange, `syncProvider` handles sinking the data and managing streams according to kademlia
- Peers connect and establish protocol over devp2p. This uses the run function in the `stream.go` file
- Peer initialises providers
- Sync provider initialises streams according to kademlia depth (`InitPeer` function on `sync_provider.go`)
- Message exchange starts from the previous step - stream protocol requests info about wanted streams with `StreamInfoReq`. Server replies with info about streams (boundedness, cursors (previously known as `sessionIndex`) in `StreamInfoRes` message
- Client handles `StreamInfoRes`, and according to wantedness of streams, initiates `GetRange` queries to fetch the stream from the server.
- Server replies with `OfferedHashes` message for the requested range
- Client, as necessary, requests hashes from the set of `OfferedHashes` with a `WantedHashes` message
- Server delivers, as necessary, chunks wanted with `ChunkDelivery` message. This message can contain multiple chunks as needed. Also, theoretically ,multiple `ChunkDelivery` messages could be sent in reply for the same `WantedHashes` in order to optimise amounts of messages sent and according to db performance to sink the data
- Once all chunks for a requested range are delivered, the interval in the interval store is sealed, and the next range is requested
 
related to https://github.com/ethersphere/user-stories/issues/2
fixes https://github.com/ethersphere/swarm/issues/1451
somewhat fixes https://github.com/ethersphere/swarm/issues/1393
closes https://github.com/ethersphere/swarm/issues/1457
closes https://github.com/ethersphere/swarm/issues/1247
closes https://github.com/ethersphere/swarm/issues/1246
closes https://github.com/ethersphere/swarm/issues/1234
closes https://github.com/ethersphere/swarm/issues/1204
closes https://github.com/ethersphere/swarm/issues/1203
closes https://github.com/ethersphere/swarm/issues/1105

### CODE REVIEW

File: network/newstream/wire.go [hunk 1]
```diff
@@ -111,7 +96,7 @@ type GetRange struct {
 	Ruid      uint
 	Stream    ID
 	From      uint64
-	To        uint64 `rlp:nil`
+	To        *uint64 `rlp:"nil"`
 	BatchSize uint
 	Roundtrip bool
```
Comment (nonsense) [inline network/newstream/wire.go]: Please remove `Roundtrip`, I really don't want to have to submit any more PRs like https://github.com/ethersphere/swarm/pull/1422 and https://github.com/ethersphere/swarm/pull/1339

I think developers on the team are smart enough to be able to add this field once they need it.

Comment (nonsense) [reply network/newstream/wire.go]: In general do not add code that is not used for no good reason. A good reason is if you will have an immediate PR that will make use of it, for example the PR with `bzz-retrieval`, even though the code was not immediately used is a good example.

File: network/newstream/sync_provider.go [hunk 2]
```diff
@@ -0,0 +1,359 @@
...
+			putSeenTestHook(addr, s.netStore.LocalID)
+		}
+	}
+	return seen, err
+}
+
+// Function used only in tests to detect chunks that are synced
+// multiple times within the same stream. This function pointer must be
+// nil in production.
+var putSeenTestHook func(addr chunk.Address, id enode.ID)
```
Comment (nonsense) [inline network/newstream/sync_provider.go]: I think this is a good use-case of something we could test if we redirect logs with a simulation. Then we could check for presence of the given log message containing `addr` and `id`. For now we don't have this functionality, so fine to leave this here, but ultimately we will be able to test this kind of impl. behaviour without custom hooks.

Just an idea.

File: network/newstream/sync_provider.go [hunk 3]
```diff
@@ -0,0 +1,359 @@
...
+	v, ok := i.(uint8)
+	if !ok {
+		return "", errors.New("error encoding key")
+	}
+	return fmt.Sprintf("%d", v), nil
+}
+
+func (s *syncProvider) StreamName() string { return s.name }
+
+func (s *syncProvider) Boundedness() bool { return false }
```
Comment (nonsense) [inline network/newstream/sync_provider.go]: I fail to see why we need `Boundedness` and `Bound`. Why do we add such indirection without using it. If this is so important how come we don't have an implementation of it.

From the spec:
`when a client requests a bounded range, server should respond to the client range requests with either offered hashes (if roundtrip is required) or chunks (if not) or an end-of-batch message if there are no more to offer. If none of these responses arrive within a timeout interval, client must drop the upstream peer.`

We don't have an example of `Boundedness` or of `Roundtrip`, so I fail to see why this is useful, apart from introducing indirection in already not simple functionality. We've been working on `pull-sync` new version for months, the previous version has been buggy in production for probably more than a year (and still throwing subscription errors), but we still continue to add code prematurely so that we make our lives harder...

File: swarm.go [hunk 4]
```diff
@@ -196,18 +198,12 @@ func NewSwarm(config *api.Config, mockStore *mock.NodeStore) (self *Swarm, err e
 		self.accountingMetrics = protocols.SetupAccountingMetrics(10*time.Second, filepath.Join(config.Path, "metrics.db"))
 	}
 
-	syncing := stream.SyncingAutoSubscribe
-	if !config.SyncEnabled || config.LightNodeEnabled {
-		syncing = stream.SyncingDisabled
-	}
+	//if !config.SyncEnabled || config.LightNodeEnabled {
```
Comment (nonsense) [inline swarm.go]: You are already unhooking the old `stream` protocol, so please remove this code, not just commented out, and also remove all the code in `network/stream` that is no longer used. No point in keeping it around, specially when it is not hooked up anymore here in `swarm.go`, and we are directly switching to the new implementation.

File: network/newstream/cursors_test.go [hunk 5]
```diff
@@ -0,0 +1,646 @@
...
+		// should not have anything shallower than depth
+		id := NewID("SYNC", fmt.Sprintf("%d", i))
+		if _, ok := onesCursors[id.String()]; ok {
+			return fmt.Errorf("oneCursors contains id %s, but it should not", id)
+		}
+	}
+	return nil
+}
+
+func TestCorrectCursorsExchangeRace(t *testing.T) {
```
Comment (nonsense) [inline network/newstream/cursors_test.go]: The mental taxation in understanding what this is doing is a bit too high for my taste. I'm happy we have started to push away complexity from production Swarm code, but we should probably rethink the complexity in tests or at least be mindful about that.

It is not immediately obvious what this test is testing. Tests should generally be simple and I shouldn't have to read the code and think for 15min to figure that out. What is this testing?

1. We are using a simulation framework.
2. We are mocking a devp2p protocol and injecting some custom hook
3. We are building peer fixtures using the p2p library.

We should probably be building more tools to write tests in a more simple manner.

No action required (or at least I don't know what I would expect), but this is def. not the direction we should be going in general IMO.

**Comment by nonsense** [comment]
@acud @janos overall great work. I don't see any blockers from my side. I've added a few comments, and talked to @acud off-band about some things that need to be fleshed out, but nothing major.

1. I still see some missing Godoc and left out commented code - it'd be nice to fix this prior to merging.
2. I think we should remove asap the `stream` folder with the previous version of the `stream` protocol - it is no longer used or hooked up, so no need to have dead code in the codebase.
3. I really think we should not add "code to be used in the future" such as Bounded streams and Roundtrip fields that serve no purpose. I've explained multiple times my opinion on that, I leave it up to you to decide.
4. Grafana dashboards are not up-to-date with the new `bzz-stream` protocol - please fix them - namely the `P2P` dashboard. I also suggest adding a bit of timers around pull-syncing batches, so that we have a baseline of how fast the pull-syncing is, and how much time it takes to request/deliver a batch. I'm sure you can figure out other interesting operational metrics that we should monitor, so that we have a baseline and improve on it. We spoke off-band about that with @acud 
5. Jaeger HTTP GET traces appear to be missing the `po` log lines for some reason. Not a big deal, but nice to have. I tried to fix this quickly, but failed, not sure whats wrong with the OpenTracing span.
6. I am not very happy with our custom use of mocked protocols and service functions... this is one of the reasons we are building the new simulation framework that will always start a production Swarm node. I think we can write better tests in general, and by better I mean - easier to reason about, easier to understand, and easier to maintain. Right now the tests are definitely not easy to understand or read, and I don't think they are very maintainable. At the same time I understand that right now, today, we don't have these tools, so I can understand why you wrote those tests the way you did. For now at least improve on the Godoc on them to make things slightly easier for the reader.

These are my general comments. The most important thing is that the code seems to be correct and integration tests seem to be passing, so I see this generally as an improvement to `master`, and think we can move forward with it.

File: network/newstream/stream.go [hunk 6]
```diff
@@ -99,27 +131,825 @@ func (s *SlipStream) removePeer(p *Peer) {
...
+		}
+	}
+	if batchStartID == nil {
+		// if batch start id is not set, it means we timed out
+		return nil, 0, 0, true, nil
+	}
+	return batch, *batchStartID, batchEndID, false, nil
+}
+
+func (s *SlipStream) PeerCursors() string {
```
Comment (nonsense) [inline network/newstream/stream.go]: It appears that you are adding this API endpoint for humans to query over Websocket for debug purposes.

It might be helpful if this returns a structured JSON output, so that this API is not only human readable, but also we can use it in integration tests, if this even makes sense.

Just an idea.

**Comment by zelig** [comment]
@acud @janos 

We created a super spec for stream! and didnt implement it. instead we implement a temporary mix of sync and stream which was identified as a problem with the current implementation.

This PR saw the tension between two different approaches one that condones any abstraction in the spirit of 'just write what the thing should do now nothing more' type of simplicity on the one hand and
the other side which cherishes clearly identified and sees simplicity, approachability and testability in the correct separation of concerns in the form of the right abstractions.

I kindly ask you to consider the following simple sketchy architecture. and think how  much it would simplify testing, help understanding and incrementally PR-ing this thing.

Thanks

```golang
package stream

// Range represents a closed interval
type Range struct {
	From, To uint64 // closed interval
}

// individual streams - no need for actual interface
type Stream interface {
	String() string
	Bound() bool
}

// Provider manages the source of a type of stream
// this is completely stateless
type Provider interface {
	Type() string                                                 // Name of provider, eg. SYNC
	CanHandle(Name) (lastIndex uint64, bound bool, err error) // provider can serve the stream given as argument, return cursor, boundedness and an  error if not provided
	OfferedHashes(Name, Range) []Address                          // returns the offered hashes for the given range
	GetDataByHash(Name, ...Address) []Chunk                       // retrieves the chunks based on Address
}

// Streamer implements Registry interface to be used in provider packages
//
type Registry interface {
	Register(Provider) error
}

// LocalStoreProvider wraps localstore and implements GetDataByHash call with localstore get
type LocalStoreProvider struct {
	localStore
}

func (l *LocalProvider) GetDataByHash(ctx context.Context, hash []byte) (chunk.Chunk, error) {
	return l.localStore.Get(ctx, chunk.ModeGetSync, hash)
}

// Client Logic
// Request Object - no need for interface, just to show methods
type Request interface {
	Cancel()
	Done() (close <-chan struct{}) // like in context
	Err()                          // error to extract after Done() closed
}

// Peer - this is not an interface just demonstrating the relevant methods
type Peer interface {
	GetRange(ctx context.Context, n Name, r Range, need func([]byte) bool, deliver func(Chunk) error) (Request, error)
	Providers() []Info
}

// NetStoreClient is a stream client that
// - proxies need function as localstore Has
// - puts chunk in netstore
// These clients are stateless
type StorerClient struct {
	Streamer
	intervals IntervalStore
	store     NetStore
	need      func([]byte) bool // implements it with netStore.Has and opens a fetcher
	deliver   func(Chunk) error // implements it with netStore.Put chunk.ModePutSync
}

// Request will try to cover the indicated range using interval store
// and peer requests for each gap in the intervals
func (s *StorerClient) Request(p Peer, n Name, r Range) (Request, error) {
	// starts a go routine that keeps getting the intervals based on the interval store
	// continuously requesting subranges according to the interval store
	// and calls
	p.GetRange(ctx, n, r, s.need, s.deliver)
	//  as batches are sealed, intervals are updated
	// the request is alive until the whole range is covered
}

// and now the level doing full sync of a stream
type Mode = uin64

const (
	History Mode = iota
	Live
	Both
)

// StorerClient implements Syncer, here stream.Syncer means syncing a stream
// only interface  used by the pull syncer client
type Syncer interface {
	Request(Context, Peer, Name, Mode) (Request, error)
	// this falls back to until cursor (history) and from cursor (live) range requests from the StorerClient
	//
}

////////////////////////////
// package pullsync

// pullSync.Server implements stream.Provider
// uses localstore SubscribePull for the  bins
// server is node-wide
type Server struct {
	// ...
	*stream.LocalProvider
}

// the node-wide pullsync.Client
type Client struct {
	stream.Syncer // embed stream.Syncer
	// when pullsync
	// here  you simply put the update sync logic listening to kademlia depth changes
	// and call `Request` 
        // remember the request, when no longer relevant just call request.Cancel()
}
```

**Comment by acud** [comment]
> We created a super spec for stream! and didnt implement it. 

This is argumentative. The stream! spec does not specify the architecture and amounts of abstractions you specified above, but rather the basic notions of which messages are exchanged, at which order, also which notions the protocol defines about indexes etc.

> instead we implement a temporary mix of sync and stream which was identified as a problem with the current implementation.

the problems with the current `stream` is the lack of proper tracing, convoluted implementation that is impossible to follow. the `stream` protocol itself already suffers from being very complex and your abstractions don't solve that problem in any way. the amount of messages that are defined in the protocol and the possible intersecting points of different messages at different points create A LOT of overhead and business logic. again, your abstractions don't solve this situation.

> This PR saw the tension between two different approaches one that condones any abstraction in the spirit of 'just write what the thing should do now nothing more' type of simplicity on the one hand and
the other side which cherishes clearly identified and sees simplicity, approachability and testability in the correct separation of concerns in the form of the right abstractions.

This PR has seen zero tensions because you have never bothered to comment on any of this code that was there in plain sight for two months. You agreed to give me liberty to proceed with a first iteration to get this merged so that we could achieve the 100gb milestone and stability milestone end of this month. Now you are acting as if the mandate was never there and you are demanding a rewrite that will not bring us any closer to stability in the near future. The abstractions you're asking to implement need more iterations (I find some of the logic you're demanding to be implemented as misplaced. This vets more discussion and I feel this will take much longer than we think) and and they will _never_ be implemented by the end of this month. To add on top of this, you know very well that @nonsense is going to adamantly object to some of the things you are suggesting here. As of such I won't proceed to discuss _any_ of this without his presence.

Furthermore, I find it insulting to ask for a redesign 3 weeks before the deadline. You should be mindful about the efforts people in the team are making in order to achieve our mutual milestones. Mind you, this process has started because of the 100gb milestone we have for the end of the month. Not as a competition of _who makes the most composite abstraction_. By asking for a redesign at this point you are not only hindering our efforts to achieve this milestone but practically sabotaging it.

- This PR brings performance improvements with an order of magnitude over the existing `stream` codebase. You are ignoring this. 
- This PR is very well tested over the existing `stream` that just throws data over a cluster and hopes for the best. You are ignoring this.
- This PR brings better tracing and logging to the `stream` package to a level where we can actually find bugs and fix them. You choose to ignore this.
- This PR makes sure that chunks get to their rightful places. You again choose to ignore this fact.

Given all of the aforementioned, I will bring this PR to a state in which it is merge-able in its current form and I strictly won't redesign it. As I said I am willing to refactor the component that handles kademlia notions our of the sync provider, I have not done this since there was enough on my plate and bringing this code to a good level of stability was a more involved task than expected.


To conclude, I won't redesign this, not until you and @nonsense finish with your pissing competition about how this should be done, as surely the amount of piss you two can dispense is immeasurably superior to mine.

Thanks

File: network/newstream/sync_provider.go [hunk 7]
```diff
@@ -0,0 +1,469 @@
...
+	for i, v := range seen {
+		if v {
+			if putSeenTestHook != nil {
+				// call the test function if it is set
+				putSeenTestHook(ch[i].Address(), s.netStore.LocalID)
+			}
+		}
+	}
+	go func(chunks ...chunk.Chunk) {
+		s.cacheMtx.Lock()
```
Comment (zelig) [inline network/newstream/sync_provider.go]: better have cache in a separate object

File: network/newstream/testing/snapshot_4.json [hunk 8]
```diff
@@ -0,0 +1 @@
...te_key":"d77006035afa5194053c0347021f7825a71f9643028c45b65756ef88ee53e6dd","name":"node_675cfed0a7b461f43cfebd6a10ecc8868d35b245381d731abec4608b6dce250a","services":["streamer"],"enable_msg_events":true,"port":37069},"up":true}}],"conns":[{"one":"0b405ded87ce4e712aaebb3055e70716c971fe049a54961294c7a7a0471d12f6","other":"a4301045c0cde5acb5406e1fba46ec868c056439ab43ef795830748fb6ba2e5a","up":true},{"one":"a4301045c0cde5acb5406e1fba46ec868c056439ab43ef795830748fb6ba2e5a","other":"77ba145a4623b9c83e0a14a375ba49c68719f2abe162ffca66de7ef2e31a75f8","up":true},{"one":"77ba145a4623b9c83e0a14a375ba49c68719f2abe162ffca66de7ef2e31a75f8","other":"675cfed0a7b461f43cfebd6a10ecc8868d35b245381d731abec4608b6dce250a","up":true},{"one":"675cfed0a7b461f43cfebd6a10ecc8868d35b245381d731abec4608b6dce250a","other":"0b405ded87ce4e712aaebb3055e70716c971fe049a54961294c7a7a0471d12f6","up":true},{"one":"77ba145a4623b9c83e0a14a375ba49c68719f2abe162ffca66de7ef2e31a75f8","other":"0b405ded87ce4e712aaebb3055e70716c971fe049a54961294c7a7a0471d12f6","up":true},{"one":"a4301045c0cde5acb5406e1fba46ec868c056439ab43ef795830748fb6ba2e5a","other":"675cfed0a7b461f43cfebd6a10ecc8868d35b245381d731abec4608b6dce250a","up":true}]}
```
Comment (zelig) [inline network/newstream/testing/snapshot_4.json]: please just use the snapshots  in`network/stream/testing`

File: storage/netstore.go [hunk 9]
```diff
@@ -155,16 +172,14 @@ func (n *NetStore) Get(ctx context.Context, mode chunk.ModeGet, req *Request) (C
...
 	ch, err := n.Store.Get(ctx, mode, ref)
 	if err != nil {
 		// TODO: fix comparison - we should be comparing against leveldb.ErrNotFound, this error should be wrapped.
 		if err != ErrChunkNotFound && err != leveldb.ErrNotFound {
-			log.Error("localstore get error", "err", err)
+			n.logger.Error("localstore get error", "err", err)
 		}
 
-		log.Trace("netstore.chunk-not-in-localstore", "ref", ref.String())
+		//n.logger.Trace("netstore.chunk-not-in-localstore", "ref", ref.String())
```
Comment (zelig) [inline storage/netstore.go]: ^

**Review by zelig — CHANGES_REQUESTED** [review]
ok for moral's sake lets just merge this PR after some critical changes. The rest should be addressed in subsequent PRs.


- there is a lot of changes in packages totally unrelated to this PR, (docker, pyramid chunker, etc) quite a few unnecessary
-  filestore, hasherstore, localstore and intervals store changes are  important and unexplained
- the package should be in `network/stream/v2` and `newstream` should be dropped
- error handling and peer drops could be massively simplified
- select on routine termination conditions are scattered around in  many unnecessary places
- the technical debt this PR introduces is way too high. Lets avoid this in future

File: Dockerfile.alltools [hunk 10]
```diff
@@ -8,6 +8,12 @@ FROM ethereum/client-go:v1.8.27 as geth
 
 FROM alpine:3.9
 RUN apk --no-cache add ca-certificates
+RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
+RUN apk --update add perf
+RUN wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
+RUN chmod +x /jq-linux64
```
Comment (nonsense) [inline Dockerfile.alltools]: I am not sure why we need `jq` and `websocat` within the image. What is the use-case here? I use those tools from my local machine, why do we need them in the `swarm` binary?

File: cmd/swarm-smoke/upload_and_sync.go [hunk 11]
```diff
@@ -47,7 +47,7 @@ func uploadAndSyncCmd(ctx *cli.Context) error {
 		seed = inputSeed
 	}
 
-	randomBytes := testutil.RandomBytes(seed, filesize*1000)
+	randomBytes := testutil.RandomBytes(seed, filesize)
```
Comment (nonsense) [inline cmd/swarm-smoke/upload_and_sync.go]: I think we should revert this. I didn't understand why we wanted to have it smaller in the first place to be honest.

File: network/newstream/common_test.go [hunk 12]
```diff
@@ -63,3 +205,111 @@ func newTestLocalStore(id enode.ID, addr *network.BzzAddr, globalStore mock.Glob
...
+		}
+		if exists[0] {
+			return nil, errors.New("generated already existing chunk")
+		}
+		chunks = append(chunks, c.Address())
+	}
+	return chunks, nil
+}
+
+func mustUploadChunks(ctx context.Context, t testing.TB, store chunk.Store, count uint64) (chunks []chunk.Address) {
```
Comment (nonsense) [inline network/newstream/common_test.go]: I think in `must` functions, generally `t` should be the first argument.

File: network/newstream/stream.go [hunk 13]
```diff
@@ -17,151 +17,1108 @@
...
+	}
+
+	// check which hashes to get from the localstore
+	for i := 0; i < l; i++ {
+		hash := o.hashes[i*HashSize : (i+1)*HashSize]
+		if want.Get(i) {
+			metrics.GetOrRegisterCounter("network.stream.handle_wanted.want_get", nil).Inc(1)
+			wantHashes = append(wantHashes, hash)
+		}
+		allHashes[i] = hash
```
[the remark this answers is not in the document]
Comment (janos) [reply network/newstream/stream.go]: All hashes are needed for mode set sync. If the peer does not want some hashes, it means that it already has them. Until we have a confirmation protocol that proves that, we need to set all hashes to sync state so that they can be garbage collected.

File: network/newstream/stream.go [hunk 14]
```diff
@@ -17,151 +17,1108 @@
...
+		delete(r.peers, p.ID())
+		close(p.quit)
+	}
+	streamPeersCount.Update(int64(len(r.peers)))
+}
+
+// PeerInfo holds information about the peer and it's peers.
+type PeerInfo struct {
+	Base      string                       `json:"base"` // our node's base address
+	Kademlia  string                       `json:"kademlia"`
```
[the remark this answers is not in the document]
Comment (janos) [reply network/newstream/stream.go]: That was useful to get kademlia information beside the cursors and intervals when debugging syncer, so that synced streams can be compared.

File: storage/filestore.go [hunk 15]
```diff
@@ -68,15 +69,16 @@ func NewLocalFileStore(datadir string, basekey []byte, tags *chunk.Tags) (*FileS
 	cleanup := func() {
 		localStore.Close()
 	}
-	return NewFileStore(chunk.NewValidatorStore(localStore, NewContentAddressValidator(MakeHashFunc(DefaultHash))), NewFileStoreParams(), tags), cleanup, nil
+	return NewFileStore(chunk.NewValidatorStore(localStore, NewContentAddressValidator(MakeHashFunc(DefaultHash))), localStore, NewFileStoreParams(), tags), cleanup, nil
 }
 
-func NewFileStore(store ChunkStore, params *FileStoreParams, tags *chunk.Tags) *FileStore {
+func NewFileStore(store ChunkStore, putterStore ChunkStore, params *FileStoreParams, tags *chunk.Tags) *FileStore {
```
[the remark this answers is not in the document]
Comment (janos) [reply storage/filestore.go:75]: Yes, the interface can be changed only to have the Put method. This change is about performance. With localstore used for put instead netstore, the congestion on nestore put mutex is highly reduced.

File: storage/netstore.go [hunk 16]
```diff
@@ -144,6 +147,20 @@ func (n *NetStore) Put(ctx context.Context, mode chunk.ModePut, chs ...Chunk) ([
 
 // Close chunk store
 func (n *NetStore) Close() error {
+	n.putMu.Lock()
+	defer n.putMu.Unlock()
+	if n.fetchers.Len() > 0 {
```
[the remark this answers is not in the document]
Comment (janos) [reply storage/netstore.go]: Yes, this can be removed. I think that it was left as a notification if we leak fetchers.

File: swarm.go [hunk 17]
```diff
@@ -576,3 +577,19 @@ type Info struct {
 func (i *Info) Info() *Info {
 	return i
 }
+
```
[the remark this answers is not in the document]
Comment (janos) [reply swarm.go]: They are used in sync_sim.go main function to measure syncing. We can remove these methods and sync_sym, that only provided confirmation that syncing is working correctly when we have struggled with the cluster. We would not need that in the future.

File: sync_sim.go [hunk 18]
```diff
@@ -0,0 +1,252 @@
...
+		bucket.Store(bucketKeyInspector, api.NewInspector(sw.API(), sw.Bzz().Hive, sw.NetStore(), sw.NewStreamer()))
+		log.Info("new swarm", "bzzKey", config.BzzKey, "baseAddr", fmt.Sprintf("%x", sw.Bzz().BaseAddr()))
+		return sw, cleanup, nil
+	}
+}
+
+func uploadRandomFile(a *api.API, length int64) (chunk.Address, string) {
+	ctx := context.Background()
+
+	hasher := md5.New()
```
[the remark this answers is not in the document]
Comment (janos) [reply sync_sim.go]: This hash is validating that the uploaded file is correctly retrieved by checkFile function.

File: sync_sim.go [hunk 19]
```diff
@@ -0,0 +1,252 @@
...
+		}
+		log.Info("sync simulation start", "iteration", i, "uploadingNode", nodeIndex)
+
+		startUpload := time.Now()
+		addr, checksum := uploadRandomFile(sim.MustNodeItem(nodes[nodeIndex], bucketKeyAPI).(*api.API), int64(*fileSize))
+		log.Info("sync simulation upload", "iteration", i, "upload", time.Since(startUpload), "checksum", checksum)
+
+		startSyncing := time.Now()
+
+		time.Sleep(1 * time.Second)
```
[the remark this answers is not in the document]
Comment (janos) [reply sync_sim.go]: This is needed to have some of the chunks exchanged by syncing, so that inspector IsPullSyncing does not return false positive.

File: sync_sim.go [hunk 20]
```diff
@@ -0,0 +1,252 @@
...
+	}
+
+	if err := wait(ctx); err != nil {
+		fatalf("wait for file to be stored: %v", err)
+	}
+
+	return key, hex.EncodeToString(hasher.Sum(nil))
+}
+
+func storeFile(ctx context.Context, a *api.API, r io.Reader, length int64, contentType string, toEncrypt bool) (k storage.Address, wait func(context.Context) error, err error) {
```
[the remark this answers is not in the document]
Comment (janos) [reply sync_sim.go]: Apparently no, but we can remove this file completely.

File: network/stream/intervals/intervals.go [hunk 21]
```diff
@@ -115,26 +115,44 @@ func (i *Intervals) Merge(m *Intervals) {
...
 // on the next interval length.
-func (i *Intervals) Next() (start, end uint64) {
+// Argument ceiling is the upper bound for the returned range.
+// Returned empty boolean indicates if both start and end values have
+// reached the ceiling value which means that the returned range is empty,
+// not containing a single element.
+func (i *Intervals) Next(ceiling uint64) (start, end uint64, empty bool) {
 	i.mu.RLock()
-	defer i.mu.RUnlock()
+	defer func() {
```
[the remark this answers is not in the document]
Comment (janos) [reply network/stream/intervals/intervals.go:129]: This is working as we are using named returned parameters.

File: network/stream/intervals/intervals.go [hunk 22]
```diff
@@ -115,26 +115,44 @@ func (i *Intervals) Merge(m *Intervals) {
...
+			}
+			empty = ceilingHitStart && ceilingHitEnd
+		}
+		i.mu.RUnlock()
+	}()
 
 	l := len(i.ranges)
 	if l == 0 {
-		return i.start, 0
+		return i.start, 0, false
```
[the remark this answers is not in the document]
Comment (janos) [reply network/stream/intervals/intervals.go:147]: This is actually setting empty to false, but empty is revalidated in the defer. It is tested in Test function test cases.

File: network/retrieval/retrieve.go [hunk 23]
```diff
@@ -398,27 +436,35 @@ FINDPEER:
...
+			Version: Spec.Version,
+			Length:  Spec.Length(),
+			Run:     r.runProtocol,
 		},
 	}
 }
 
+func (r *Retrieval) runProtocol(p *p2p.Peer, rw p2p.MsgReadWriter) error {
+	peer := protocols.NewPeer(p, rw, Spec)
+	// TODO: fix, used in tests only. Incorrect, as we do not have access to the overlay address
```
[the remark this answers is not in the document]
Comment (janos) [reply network/retrieval/retrieve.go]: network.NewBzzPeer is incorrect function which construct BzzAddr overlay address from enode.ID, which is used only in tests. This comment should be removed.

File: network/newstream/common_test.go (hunk 12 above)
Comment (janos) [reply network/newstream/common_test.go]: That would be expected, but linter complains about context not being the first argument.

File: network/newstream/peer.go [hunk 24]
```diff
@@ -17,83 +17,212 @@
...
+// getOfferOrDrop gets on open offer for the requested ruid
+// in case the offer is not found - the peer is dropped
+func (p *Peer) getOfferOrDrop(ruid uint) (o offer, shouldBreak bool) {
+	p.mtx.RLock()
+	o, ok := p.openOffers[ruid]
+	p.mtx.RUnlock()
+	if !ok {
+		p.logger.Error("ruid not found, dropping peer", "ruid", ruid)
+		p.Drop()
+		return o, true
```
Comment (nonsense) [inline network/newstream/peer.go]: `return nil, true`, let's be explicit that `o` is no found.

File: network/newstream/sync_provider.go (hunk 3 above)
Comment (nonsense) [reply network/newstream/sync_provider.go]: @zelig @janos this comment is still applicable. @janos no action required from your side, but if you understand this, maybe you can explain it to me :)

File: network/newstream/testing/snapshot_4.json (hunk 8 above)
Comment (nonsense) [reply network/newstream/testing/snapshot_4.json]: The idea is to remove the whole `network/stream` package. Why create references between the `new` and `old` packages, when we should have only one in the codebase?

Comment (zelig) [reply network/newstream/testing/snapshot_4.json]: @nonsense, no the idea is to reimplement streamer
- we want to use the same snapshots as before
- we want pr to be smaller
- bitvector and intervalstore are also  dependencies from old stream
- the new streamer should be in `stream/v2`

Comment (nonsense) [reply network/newstream/testing/snapshot_4.json]: OK, I was unaware that we will be maintaining both streamers. cc @janos

Comment (nonsense) [reply network/newstream/testing/snapshot_4.json]: Actually @janos is already removing it at `120c034`, which I thought is a good idea, but now I am a bit confused why we need to keep it around? @zelig why do you want to keep both `v1` and `v2`? Is there another library that is using the code in `v1`?

File: network/stream/v2/syncing_test.go [hunk 25]
```diff
@@ -0,0 +1,811 @@
...
+*/
+func BenchmarkHistoricalStream_1000(b *testing.B)  { benchmarkHistoricalStream(b, 1000) }
+func BenchmarkHistoricalStream_2000(b *testing.B)  { benchmarkHistoricalStream(b, 2000) }
+func BenchmarkHistoricalStream_3000(b *testing.B)  { benchmarkHistoricalStream(b, 3000) }
+func BenchmarkHistoricalStream_5000(b *testing.B)  { benchmarkHistoricalStream(b, 5000) }
+func BenchmarkHistoricalStream_10000(b *testing.B) { benchmarkHistoricalStream(b, 10000) }
+func BenchmarkHistoricalStream_15000(b *testing.B) { benchmarkHistoricalStream(b, 15000) }
+func BenchmarkHistoricalStream_20000(b *testing.B) { benchmarkHistoricalStream(b, 20000) }
+
+func benchmarkHistoricalStream(b *testing.B, chunks uint64) {
```
Comment (janos) [inline network/stream/v2/syncing_test.go:565]: @zelig @nonsense Could you check this benchmark also? I think that the measuring method is not correct. The simulation is constructed outside of the benchmark loop and in the benchmark loop chunks are uploaded on the same node of the same simulation, making the state on every benchmark iteration different. Every iteration measures different state and with larger number of chunks in the localstore, it becomes slower. This makes this benchmark result dependent on the number of iterations performed, where only the precisions of results should be influenced by the number of iterations. I think that this benchmark should be rewritten in a way that every iteration measures time on the independent state of other iterations, or to remove the benchmark as that may make this benchmark time consuming.

Comment (nonsense) [reply network/stream/v2/syncing_test.go:565]: @janos it does look like the benchmark is indeed not correct for the reasons you mentioned.

File: network/stream/intervals/intervals.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (zelig) [reply network/stream/intervals/intervals.go]: but which return is using them? you explicitly return false for empty
am i totally in the wrong about how this works?

File: network/stream/v2/syncing_test.go (hunk 25 above)
Comment (zelig) [reply network/stream/v2/syncing_test.go:565]: agree

**Review by zelig — APPROVED** [review]
thanks @janos for the quick cleanup and reorg, I dont like that you put in the deletion of old stream code in this PR.

i approve it but lets make sure:
- we heed the issues raised in later PRs
- we understand the changes to localstore, intervalstore, simulation, etc packages

**Comment by janos** [comment]
@zelig Thank you for the review and approval.

I will create issues on the comments that are there after this PR gets merged.

I do not mind putting back the old streamer code. Would you like to restore the files?

File: network/stream/v2/syncing_test.go (hunk 25 above)
Comment (janos) [reply network/stream/v2/syncing_test.go:565]: I have changed the benchmark to address this problem, and it is even usable.

File: network/stream/v2/snapshot_sync_test.go [hunk 26]
```diff
@@ -68,7 +68,7 @@ func TestSyncingViaGlobalSync(t *testing.T) {
 		log.Info(fmt.Sprintf("Running test with %d chunks and %d nodes...", *chunks, *nodes))
 		testSyncingViaGlobalSync(t, *chunks, *nodes)
 	} else {
-		chunkCounts := []int{4, 32}
```
Comment (nonsense) [inline network/stream/v2/snapshot_sync_test.go:92]: We can't sync 32 chunks ? :)

Comment (janos) [reply network/stream/v2/snapshot_sync_test.go:92]: It times out on travis. :) And it actually does not even flake locally. The only thing that I managed to see is the goroutine leak in hive that is fixed. If it is flaky even with only 4 chunks on travis, we should disable this test and dedicate more time to find the root cause.

**Review by nonsense — APPROVED** [review]
